const BOOKS={Genesis:50,Exodus:40,Leviticus:27,Numbers:36,Deuteronomy:34,Joshua:24,Judges:21,Ruth:4,'1 Samuel':31,'2 Samuel':24,'1 Kings':22,'2 Kings':25,'1 Chronicles':29,'2 Chronicles':36,Ezra:10,Nehemiah:13,Esther:10,Job:42,Psalms:150,Proverbs:31,Ecclesiastes:12,'Song of Solomon':8,Isaiah:66,Jeremiah:52,Lamentations:5,Ezekiel:48,Daniel:12,Hosea:14,Joel:3,Amos:9,Obadiah:1,Jonah:4,Micah:7,Nahum:3,Habakkuk:3,Zephaniah:3,Haggai:2,Zechariah:14,Malachi:4,Matthew:28,Mark:16,Luke:24,John:21,Acts:28,Romans:16,'1 Corinthians':16,'2 Corinthians':13,Galatians:6,Ephesians:6,Philippians:4,Colossians:4,'1 Thessalonians':5,'2 Thessalonians':3,'1 Timothy':6,'2 Timothy':4,Titus:3,Philemon:1,Hebrews:13,James:5,'1 Peter':5,'2 Peter':3,'1 John':5,'2 John':1,'3 John':1,Jude:1,Revelation:22};
const LANG={en:'English',tl:'Tagalog / Filipino',ceb:'Cebuano',hil:'Hiligaynon',es:'Spanish'};
const DAY=['Psalms 118:24','Joshua 1:8','Isaiah 40:31','Matthew 11:28','John 3:16','Romans 8:28','Philippians 4:13','Psalms 46:1','Proverbs 3:5','Hebrews 4:9','Mark 2:28','2 Corinthians 5:17','Revelation 14:12','Psalms 119:105'];
const NIGHT=['Psalms 4:8','Psalms 63:6','Psalms 91:1','Psalms 121:4','Psalms 139:12','Proverbs 3:24','Isaiah 26:9','Lamentations 2:19','Matthew 14:23','Mark 13:35','Luke 6:12','Acts 16:25','1 Thessalonians 5:5','Psalms 119:148'];
const EVENTS={passover:{name:'Passover',day:'1 Corinthians 5:7',night:'Exodus 12:13',theme:'Christ our Passover and deliverance through His blood'},unleavened:{name:'Feast of Unleavened Bread',day:'1 Corinthians 5:8',night:'Exodus 12:17',theme:'sincerity, truth and a cleansed walk in Christ'},firstfruits:{name:'Firstfruits',day:'1 Corinthians 15:20',night:'Matthew 28:6',theme:'the resurrection of the Lord Jesus Christ'},pentecost:{name:'Pentecost',day:'Acts 2:4',night:'John 14:16',theme:'the promised Holy Ghost and witness for Christ'},trumpets:{name:'Feast of Trumpets',day:'1 Thessalonians 4:16',night:'Matthew 25:6',theme:'watchfulness and the return of the Lord Jesus Christ'},atonement:{name:'Day of Atonement',day:'Hebrews 9:28',night:'Hebrews 4:14',theme:'Christ our sacrifice and great High Priest'},tabernacles:{name:'Feast of Tabernacles',day:'John 1:14',night:'Revelation 21:3',theme:'God dwelling with His people through Jesus Christ'},eighth:{name:'The Eighth Day',day:'John 7:37',night:'Revelation 22:17',theme:'the Lord Jesus Christ satisfying the spiritually thirsty'},sabbath:{name:'Seventh-Day Sabbath',day:'Mark 2:28',night:'Hebrews 4:9',theme:'holy rest and the Lord Jesus Christ, Lord of the Sabbath'}};
const COMMANDMENTS=[['I','No other gods','Thou shalt have no other gods before me.','Exodus 20:3'],['II','No graven images','Thou shalt not make unto thee any graven image… Thou shalt not bow down thyself to them, nor serve them…','Exodus 20:4–5'],['III','Honour God’s name','Thou shalt not take the name of the LORD thy God in vain…','Exodus 20:7'],['IV','Remember the Sabbath','Remember the sabbath day, to keep it holy. Six days shalt thou labour, and do all thy work: But the seventh day is the sabbath of the LORD thy God…','Exodus 20:8–10'],['V','Honour father and mother','Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee.','Exodus 20:12'],['VI','Do not kill','Thou shalt not kill.','Exodus 20:13'],['VII','Do not commit adultery','Thou shalt not commit adultery.','Exodus 20:14'],['VIII','Do not steal','Thou shalt not steal.','Exodus 20:15'],['IX','Do not bear false witness','Thou shalt not bear false witness against thy neighbour.','Exodus 20:16'],['X','Do not covet','Thou shalt not covet… any thing that is thy neighbour’s.','Exodus 20:17']];
const FEASTS=[['Passover','Deliverance through the blood of the lamb, fulfilled in Christ our passover.','Leviticus 23:5 · 1 Corinthians 5:7'],['Unleavened Bread','Seven days remembering deliverance and the call to sincerity and truth.','Leviticus 23:6–8'],['Firstfruits','The first sheaf, pointing to Christ risen from the dead.','Leviticus 23:9–14 · 1 Corinthians 15:20'],['Pentecost','The Feast of Weeks and a proclaimed holy convocation.','Leviticus 23:15–21 · Acts 2'],['Trumpets','A memorial of blowing of trumpets, an holy convocation.','Leviticus 23:23–25'],['Day of Atonement','A solemn day of affliction, holy convocation and sabbath of rest.','Leviticus 23:26–32'],['Tabernacles','Seven days of rejoicing before the LORD.','Leviticus 23:33–43'],['The Eighth Day','A distinct holy convocation and solemn assembly.','Leviticus 23:36, 39']];
const HYMNS=[{title:'Holy, Holy, Holy',theme:'christ feast',ref:'Revelation 4:8',lyrics:'Holy, holy, holy! Lord God Almighty!\nEarly in the morning our song shall rise to Thee;\nHoly, holy, holy! Merciful and mighty!\nGod in three Persons, blessed Trinity!'},{title:'Jesus Paid It All',theme:'christ feast',ref:'Isaiah 1:18',lyrics:'I hear the Saviour say, Thy strength indeed is small;\nChild of weakness, watch and pray, find in Me thine all in all.\nJesus paid it all, all to Him I owe;\nSin had left a crimson stain, He washed it white as snow.'},{title:'Come, Thou Fount of Every Blessing',theme:'prayer christ',ref:'1 Samuel 7:12',lyrics:'Come, Thou Fount of every blessing, tune my heart to sing Thy grace;\nStreams of mercy, never ceasing, call for songs of loudest praise.'},{title:'All Hail the Power of Jesus’ Name',theme:'christ',ref:'Philippians 2:10–11',lyrics:'All hail the power of Jesus’ name! Let angels prostrate fall;\nBring forth the royal diadem, and crown Him Lord of all.'},{title:'O Day of Rest and Gladness',theme:'sabbath',ref:'Exodus 20:8',lyrics:'O day of rest and gladness, O day of joy and light,\nO balm of care and sadness, most beautiful, most bright.'},{title:'Rock of Ages',theme:'christ prayer feast',ref:'1 Corinthians 10:4',lyrics:'Rock of Ages, cleft for me, let me hide myself in Thee;\nLet the water and the blood, from Thy wounded side which flowed,\nBe of sin the double cure, save from wrath and make me pure.'}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let bible={},book='Genesis',chapter=1,verse=1,mode='single',today={};
const ORIGINAL_TEXT=new WeakMap(),ORIGINAL_PLACEHOLDER=new WeakMap();
const clean=s=>(s||'').replace(/^#\s*/,'').replace(/\[([^\]]+)\]/g,'$1').trim();
const refText=(b=book,c=chapter,v=verse)=>`${b} ${c}:${v}`;

function eventFor(date){let p={};try{p=Object.fromEntries(new Intl.DateTimeFormat('en-u-ca-hebrew',{month:'long',day:'numeric'}).formatToParts(date).filter(x=>x.type==='month'||x.type==='day').map(x=>[x.type,x.value]));}catch{}const m=p.month,d=+p.day;if(m==='Nisan'&&d===14)return EVENTS.passover;if(m==='Nisan'&&d===16)return EVENTS.firstfruits;if(m==='Nisan'&&d>=15&&d<=21)return EVENTS.unleavened;if(m==='Sivan'&&d===6)return EVENTS.pentecost;if((m==='Tishri'||m==='Tishrei')&&d===1)return EVENTS.trumpets;if((m==='Tishri'||m==='Tishrei')&&d===10)return EVENTS.atonement;if((m==='Tishri'||m==='Tishrei')&&d>=15&&d<=21)return EVENTS.tabernacles;if((m==='Tishri'||m==='Tishrei')&&d===22)return EVENTS.eighth;if(date.getDay()===6)return EVENTS.sabbath;return null}
function dailyPair(){const n=new Date(),start=new Date(n.getFullYear(),0,0),index=Math.floor((n-start)/86400000),event=eventFor(n);return{date:n,event,day:event?.day||DAY[index%DAY.length],night:event?.night||NIGHT[index%NIGHT.length]}}
function dateLabel(d){return d.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function soapMarkup(kind,title,ref){const id=kind.toLowerCase();return `<section class="daily pad" id="${id}-section"><header class="section-head"><p class="eyebrow">Daily Bread · ${kind}</p><h2>${title}</h2><p class="date">${dateLabel(today.date)}</p></header><div class="parallel verse-pair"><article class="kjv"><h3>English · King James Version</h3><blockquote id="${id}-en" class="notranslate" translate="no">Loading Scripture…</blockquote><cite id="${id}-ref">${ref} KJV</cite></article><article><h3 id="${id}-lang">Selected language</h3><blockquote id="${id}-tr">Choose a language above. English KJV always remains beside its translation.</blockquote></article></div><div class="soap"><aside><p class="soap-letter">S</p><h3>Scripture</h3><p>Read ${ref} slowly. How does it reveal the Lord Jesus Christ?</p><p class="soap-letter">O</p><h3>Observation</h3><p>What does this verse reveal about God, His will and the condition of man?</p><p class="soap-letter">A</p><h3>Application</h3><p>What truth should I believe, obey or practise ${kind==='Day'?'today':'tonight'}?</p><p class="soap-letter">P</p><h3>Prayer</h3><p>Respond honestly to the LORD through faith in Jesus Christ.</p></aside><form data-soap="${id}"><label>Email address<input name="email" type="email" required placeholder="you@example.com"></label><label>My Observation<textarea name="observation" rows="4"></textarea></label><label>My Application<textarea name="application" rows="4"></textarea></label><label>My Prayer<textarea name="prayer" rows="4"></textarea></label><p class="status" role="status"></p><div class="soap-buttons"><button class="btn navy email-soap" type="button">Email Saved SOAP to Your Email — Free</button><button class="btn outline save-account" type="button">Save to Account — US$1/month</button><a class="btn link" href="#give">Donate to Help Keep This Ministry Online</a></div></form></div></section>`}

async function translate(text,lang){if(lang==='en'||!text)return text;const key=`lotstr:${lang}:${text}`;try{const cached=localStorage.getItem(key);if(cached)return cached}catch{}const url=`https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=${encodeURIComponent(lang)}&dt=t&q=${encodeURIComponent(text)}`;try{const r=await fetch(url);if(!r.ok)throw Error();const data=await r.json(),out=(data[0]||[]).map(x=>x[0]||'').join('');if(!out)throw Error();try{localStorage.setItem(key,out)}catch{}return out}catch{return 'Translation is temporarily unavailable. The English KJV remains available.'}}
async function translateInto(source,target,lang){const el=$(target);if(!el)return;el.textContent=lang==='en'?'English is shown in the KJV panel.':'Translating the exact KJV text…';el.textContent=await translate($(source)?.textContent||'',lang)}
async function translateInterface(lang){const nodes=[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue.trim()||n.parentElement?.closest('.notranslate,[id$="-tr"],#chapter-tr,script,style,textarea,option'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});let node;while(node=walker.nextNode()){if(!ORIGINAL_TEXT.has(node))ORIGINAL_TEXT.set(node,node.nodeValue);nodes.push(node)}const attrs=$$('input[placeholder],textarea[placeholder]');attrs.forEach(e=>{if(!ORIGINAL_PLACEHOLDER.has(e))ORIGINAL_PLACEHOLDER.set(e,e.placeholder)});if(lang==='en'){nodes.forEach(n=>n.nodeValue=ORIGINAL_TEXT.get(n));attrs.forEach(e=>e.placeholder=ORIGINAL_PLACEHOLDER.get(e));return}await Promise.all(nodes.map(async n=>{const original=ORIGINAL_TEXT.get(n),left=original.match(/^\s*/)[0],right=original.match(/\s*$/)[0];n.nodeValue=left+await translate(original.trim(),lang)+right}));await Promise.all(attrs.map(async e=>e.placeholder=await translate(ORIGINAL_PLACEHOLDER.get(e),lang)))}
async function applyInterfaceLanguage(lang){document.documentElement.lang=lang==='en'?'en':lang;await translateInterface(lang);await refreshTranslations(lang)}
async function refreshTranslations(lang){const name=LANG[lang];['day','night','motto','reader'].forEach(k=>{const e=$(`#${k}-lang`);if(e)e.textContent=lang==='en'?'English':`${name} · translated from KJV`});await Promise.all([translateInto('#day-en','#day-tr',lang),translateInto('#night-en','#night-tr',lang),translateInto('#motto-en','#motto-tr',lang),renderReaderTranslation(lang)]);if(mode==='chapter')renderFullChapter(lang);renderHymns()}

function getVerse(b,c,v){return clean(bible[`${b} ${c}:${v}`])}
function verseCount(b,c){let n=0;while(n<200&&getVerse(b,c,n+1))n++;return n}
function populateBooks(){const s=$('#book-select');Object.keys(BOOKS).forEach(b=>s.add(new Option(b,b)));s.value=book;populateChapters()}
function populateChapters(){const s=$('#chapter-select');s.innerHTML='';for(let i=1;i<=BOOKS[book];i++)s.add(new Option(i,i));s.value=chapter;populateVerses()}
function populateVerses(){const s=$('#verse-select'),n=verseCount(book,chapter)||1;s.innerHTML='';for(let i=1;i<=n;i++)s.add(new Option(i,i));verse=Math.min(verse,n);s.value=verse}
function renderSingle(){mode='single';$('#single-reading').hidden=false;$('#chapter-reading').hidden=true;const ref=refText(),text=getVerse(book,chapter,verse);$('#reader-en').textContent=text?`“${text}”`:'Verse unavailable.';$('#reader-ref').textContent=`${ref} KJV`;$('#reader-tr-ref').textContent=ref;renderReaderTranslation($('#site-language').value);$('#prev-verse').disabled=book==='Genesis'&&chapter===1&&verse===1;$('#next-verse').disabled=book==='Revelation'&&chapter===22&&verse===verseCount(book,chapter)}
async function renderReaderTranslation(lang=$('#site-language').value){$('#reader-tr').textContent=lang==='en'?'English is shown in the KJV panel.':'Translating the exact KJV verse…';$('#reader-tr').textContent=await translate(getVerse(book,chapter,verse),lang)}
function moveVerse(delta){const books=Object.keys(BOOKS);verse+=delta;if(verse<1){if(chapter>1){chapter--;verse=verseCount(book,chapter)}else{let i=books.indexOf(book);if(i===0){verse=1;return}book=books[i-1];chapter=BOOKS[book];verse=verseCount(book,chapter)}}else if(verse>verseCount(book,chapter)){if(chapter<BOOKS[book]){chapter++;verse=1}else{let i=books.indexOf(book);if(i===books.length-1){verse=verseCount(book,chapter);return}book=books[i+1];chapter=1;verse=1}}$('#book-select').value=book;populateChapters();$('#chapter-select').value=chapter;populateVerses();$('#verse-select').value=verse;renderSingle()}
async function renderFullChapter(lang=$('#site-language').value){mode='chapter';$('#single-reading').hidden=true;$('#chapter-reading').hidden=false;const n=verseCount(book,chapter),en=$('#chapter-en'),tr=$('#chapter-tr');$('#chapter-en-title').textContent=`${book} ${chapter} · English KJV`;$('#chapter-tr-title').textContent=`${book} ${chapter} · ${LANG[lang]}`;en.innerHTML='';tr.innerHTML=lang==='en'?'<p>English KJV is displayed beside this panel.</p>':'<p>Translating the exact KJV chapter…</p>';for(let i=1;i<=n;i++){const p=document.createElement('p');p.dataset.v=i;p.className=i===verse?'selected':'';p.innerHTML=`<sup>${i}</sup>${escapeHtml(getVerse(book,chapter,i))}`;en.append(p)}if(lang!=='en'){tr.innerHTML='';for(let start=1;start<=n;start+=12){const end=Math.min(n,start+11),texts=[];for(let i=start;i<=end;i++)texts.push(`[[${i}]] ${getVerse(book,chapter,i)}`);const out=await translate(texts.join('\n'),lang);const blocks=out.split(/\[\[(\d+)\]\]/).slice(1);for(let j=0;j<blocks.length;j+=2){const p=document.createElement('p'),v=+blocks[j];p.className=v===verse?'selected':'';p.innerHTML=`<sup>${v}</sup>${escapeHtml((blocks[j+1]||'').trim())}`;tr.append(p)}}}setTimeout(()=>en.querySelector('.selected')?.scrollIntoView({block:'center'}),20)}
function moveChapter(delta){const books=Object.keys(BOOKS);chapter+=delta;if(chapter<1){const i=books.indexOf(book);if(!i){chapter=1;return}book=books[i-1];chapter=BOOKS[book]}else if(chapter>BOOKS[book]){const i=books.indexOf(book);if(i===books.length-1){chapter=BOOKS[book];return}book=books[i+1];chapter=1}verse=1;$('#book-select').value=book;populateChapters();renderFullChapter()}
const escapeHtml=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function emailSoap(form){const status=form.querySelector('.status'),button=form.querySelector('.email-soap'),kind=form.dataset.soap,email=form.email.value.trim();if(!form.reportValidity())return;if(!form.observation.value.trim()&&!form.application.value.trim()&&!form.prayer.value.trim()){status.textContent='Please write at least one SOAP entry.';return}button.disabled=true;button.textContent='Sending…';const ref=kind==='day'?today.day:today.night;try{const r=await fetch('send-soap.php',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({email,reference:ref,scripture:$(`#${kind}-en`).textContent,observation:form.observation.value,application:form.application.value,prayer:form.prayer.value,website:''})}),data=await r.json().catch(()=>({}));if(!r.ok||!data.success)throw Error(data.message||'Email could not be sent.');status.textContent='Your SOAP journal has been emailed. Please check your inbox and spam folder.'}catch(e){status.textContent=e.message||'Email could not be sent. Please try again.'}finally{button.disabled=false;button.textContent='Email Saved SOAP to Your Email — Free'}}
function preserveSoap(form){['observation','application','prayer'].forEach(n=>{const key=`soap:${form.dataset.soap}:${dateLabel(today.date)}:${n}`,f=form[n];f.value=sessionStorage.getItem(key)||'';f.addEventListener('input',()=>sessionStorage.setItem(key,f.value))})}

function renderHymns(){const q=($('#hymn-search')?.value||'').toLowerCase(),f=$('#hymn-filter')?.value||'all',event=today.event;let hymns=HYMNS.filter(h=>(f==='all'||h.theme.includes(f))&&(`${h.title} ${h.ref} ${h.theme}`.toLowerCase().includes(q)));if(event)hymns.sort((a,b)=>Number(b.theme.includes(event===EVENTS.sabbath?'sabbath':'feast'))-Number(a.theme.includes(event===EVENTS.sabbath?'sabbath':'feast')));$('#hymn-season').textContent=event?`Recommended for ${event.name}: ${event.theme}.`:'Public-domain hymns centred upon Scripture and the Lord Jesus Christ.';$('#hymn-list').innerHTML=hymns.map(h=>`<article><p class="eyebrow">${event&&h.theme.includes(event===EVENTS.sabbath?'sabbath':'feast')?'Recommended today':'Public domain'}</p><h2>${h.title}</h2><cite>${h.ref}</cite><pre>${h.lyrics}</pre></article>`).join('')||'<p>No hymns match your search.</p>'}
function route(){const id=location.hash.slice(1)||'home',page=document.getElementById(id)||$('#home');$$('.page').forEach(p=>p.classList.toggle('active',p===page));$$('#nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${page.id}`));document.title=`${page.dataset.title} | Lord of the Sabbath Church`;$('#nav').classList.remove('open');$('.menu').setAttribute('aria-expanded','false');scrollTo(0,0)}
function buildStatic(){today=dailyPair();$('#daily-mount').innerHTML=soapMarkup('Day','Verse of the Day',today.day)+soapMarkup('Night','Verse of the Night',today.night);$('#calendar-title').textContent=today.event?today.event.name:'Daily KJV meditation';$('#calendar-note').textContent=today.event?`Today’s verses, SOAP guidance and hymns emphasize ${today.event.theme}. Content dates change at local midnight; biblical observances are identified from the biblical calendar.`:'The Day and Night verses change together at local midnight.';$('#commandments-list').innerHTML=COMMANDMENTS.map(x=>`<article><b>${x[0]}</b><h2>${x[1]}</h2><blockquote>“${x[2]}”</blockquote><cite>${x[3]} KJV</cite></article>`).join('');$('#feast-list').innerHTML=FEASTS.map((x,i)=>`<article><b>0${i+1}</b><h2>${x[0]}</h2><p>${x[1]}</p><cite>${x[2]}</cite></article>`).join('');['day','night'].forEach(k=>{const ref=today[k],text=getVerse(...Object.values(parseRef(ref)));$(`#${k}-en`).textContent=text?`“${text}”`:'Scripture unavailable.';document.querySelector(`form[data-soap="${k}"] .email-soap`).addEventListener('click',e=>emailSoap(e.target.form));document.querySelector(`form[data-soap="${k}"] .save-account`).addEventListener('click',e=>{e.target.form.querySelector('.status').textContent='Secure account subscriptions require the payment gateway to be connected. Your writing remains safely in this browser for this session.'});preserveSoap(document.querySelector(`form[data-soap="${k}"]`))});renderHymns()}
function parseRef(ref){const m=ref.match(/^(.+?) (\d+):(\d+)$/);return{book:m[1],chapter:+m[2],verse:+m[3]}}
function events(){window.addEventListener('hashchange',route);$('.menu').onclick=e=>{const open=$('#nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)};$('#site-language').onchange=e=>applyInterfaceLanguage(e.target.value);$('#book-select').onchange=e=>{book=e.target.value;chapter=verse=1;populateChapters();renderSingle()};$('#chapter-select').onchange=e=>{chapter=+e.target.value;verse=1;populateVerses();renderSingle()};$('#verse-select').onchange=e=>{verse=+e.target.value;renderSingle()};$('#prev-verse').onclick=()=>moveVerse(-1);$('#next-verse').onclick=()=>moveVerse(1);$('#full-chapter').onclick=()=>renderFullChapter();$('#close-chapter').onclick=renderSingle;$('#prev-chapter').onclick=()=>moveChapter(-1);$('#next-chapter').onclick=()=>moveChapter(1);$('#hymn-search').oninput=renderHymns;$('#hymn-filter').onchange=renderHymns;$('#donate').onclick=()=>$('#donate-status').textContent='The secure Flik payment gateway will become available after the ministry’s merchant account and checkout credentials are approved and connected. No payment information has been collected.'}
async function init(){try{const r=await fetch('assets/kjv-1769.json');if(!r.ok)throw Error();bible=await r.json()}catch{$('#daily-mount').innerHTML='<p class="error">The Bible data could not be loaded. Please refresh.</p>';return}buildStatic();populateBooks();renderSingle();events();route();$('#year').textContent=new Date().getFullYear();setTimeout(()=>{const c=$('.goog-te-combo');if(c)c.setAttribute('aria-label','Google website translation')},2500)}
init();
