const BOOKS={
  Genesis:50,Exodus:40,Leviticus:27,Numbers:36,Deuteronomy:34,Joshua:24,Judges:21,Ruth:4,
  '1 Samuel':31,'2 Samuel':24,'1 Kings':22,'2 Kings':25,'1 Chronicles':29,'2 Chronicles':36,Ezra:10,Nehemiah:13,Esther:10,Job:42,Psalms:150,Proverbs:31,Ecclesiastes:12,
  'Song of Solomon':8,Isaiah:66,Jeremiah:52,Lamentations:5,Ezekiel:48,Daniel:12,Hosea:14,Joel:3,Amos:9,Obadiah:1,Jonah:4,Micah:7,Nahum:3,Habakkuk:3,Zephaniah:3,Haggai:2,Zechariah:14,Malachi:4,
  Matthew:28,Mark:16,Luke:24,John:21,Acts:28,Romans:16,'1 Corinthians':16,'2 Corinthians':13,Galatians:6,Ephesians:6,Philippians:4,Colossians:4,'1 Thessalonians':5,'2 Thessalonians':3,'1 Timothy':6,'2 Timothy':4,Titus:3,Philemon:1,Hebrews:13,James:5,'1 Peter':5,'2 Peter':3,'1 John':5,'2 John':1,'3 John':1,Jude:1,Revelation:22
};
const LANGUAGES=['English KJV','Colombian Spanish','Chinese','Korean','French','Norwegian','Swedish','Tagalog','Cebuano','Italian'];
const DAILY_REFS=['Psalms 118:24','Joshua 1:8','Isaiah 40:31','Matthew 11:28','John 3:16','Romans 8:28','Philippians 4:13','Psalms 46:1','Proverbs 3:5','Hebrews 4:9','Mark 2:28','2 Corinthians 5:17','Revelation 14:12','Psalms 119:105'];
let bibleData={};let currentBook='Genesis';let currentChapter=1;let dailyRef='Joshua 1:8';let highlightRef='';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];

function cleanVerse(text=''){return text.replace(/^#\s*/, '').replace(/\[([^\]]+)\]/g,'$1').trim()}
function populateLanguages(){['#daily-language','#reader-language'].forEach(selector=>{const el=$(selector);LANGUAGES.forEach(lang=>{const option=document.createElement('option');option.value=lang;option.textContent=lang;el.append(option)});el.value=selector==='#daily-language'?'Colombian Spanish':'English KJV'})}
function parseRef(ref){const match=ref.match(/^(.+?)\s(\d+)(?::(\d+))?$/);return match?{book:match[1],chapter:Number(match[2]),verse:match[3]?Number(match[3]):null}:null}
function updateDaily(){const now=new Date();const start=new Date(now.getFullYear(),0,0);const day=Math.floor((now-start)/86400000);dailyRef=DAILY_REFS[day%DAILY_REFS.length];$('#verse-date').textContent=now.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'});$('#daily-reference').textContent=`${dailyRef} KJV`;$('#daily-kjv').textContent=bibleData[dailyRef]?`“${cleanVerse(bibleData[dailyRef])}”`:'“This book of the law shall not depart out of thy mouth…”';$('#soap-scripture').textContent=`Read ${dailyRef} slowly and prayerfully. What words or truths stand out?`;updateTranslation('#daily-language','#daily-translation')}
function updateTranslation(selectId,targetId){const lang=$(selectId).value;const target=$(targetId);if(lang==='English KJV'){target.textContent='The authoritative English KJV text is shown beside this panel.'}else{target.textContent=`${lang} parallel text is prepared for connection. The English KJV will always remain visible beside it.`}}
function populateBooks(){const select=$('#book-select');Object.keys(BOOKS).forEach(book=>{const option=document.createElement('option');option.value=book;option.textContent=book;select.append(option)});select.value=currentBook;populateChapters()}
function populateChapters(){const select=$('#chapter-select');select.innerHTML='';for(let i=1;i<=BOOKS[currentBook];i++){const option=document.createElement('option');option.value=i;option.textContent=i;select.append(option)}select.value=currentChapter}
function renderChapter(){const title=`${currentBook} ${currentChapter}`;$('#chapter-title').textContent=title;const container=$('#chapter-verses');container.innerHTML='';let found=false;for(let v=1;v<=176;v++){const ref=`${title}:${v}`;if(!bibleData[ref]){if(found)break;continue}found=true;const p=document.createElement('p');p.innerHTML=`<sup>${v}</sup>${cleanVerse(bibleData[ref])}`;if(ref===highlightRef)p.classList.add('highlighted');container.append(p)}if(!found)container.innerHTML='<p>The KJV chapter could not be loaded. Please refresh the page.</p>';$('#previous-chapter').disabled=currentBook==='Genesis'&&currentChapter===1;$('#next-chapter').disabled=currentBook==='Revelation'&&currentChapter===22;const lang=$('#reader-language').value;$('#translation-name').textContent=lang;$('#translation-note').textContent=lang==='English KJV'?'The same English KJV chapter is displayed on the left. Choose another language for the future parallel panel.':`${lang} parallel chapter text is prepared for connection. The English KJV remains visible on the left.`;if(highlightRef)setTimeout(()=>container.querySelector('.highlighted')?.scrollIntoView({block:'center'}),50)}
function changeChapter(delta){const books=Object.keys(BOOKS);let index=books.indexOf(currentBook);currentChapter+=delta;if(currentChapter<1&&index>0){currentBook=books[index-1];currentChapter=BOOKS[currentBook]}else if(currentChapter>BOOKS[currentBook]&&index<books.length-1){currentBook=books[index+1];currentChapter=1}highlightRef='';$('#book-select').value=currentBook;populateChapters();renderChapter()}
function openReference(ref){const parsed=parseRef(ref);if(!parsed||!BOOKS[parsed.book])return;currentBook=parsed.book;currentChapter=parsed.chapter;highlightRef=parsed.verse?ref:'';location.hash='bible';$('#book-select').value=currentBook;populateChapters();renderChapter()}
function route(){const requested=location.hash.slice(1)||'home';const page=document.getElementById(requested)||$('#home');$$('.page').forEach(p=>p.classList.toggle('active',p===page));$$('.site-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${page.id}`));document.title=page.dataset.title||'Lord of the Sabbath Church';$('.site-nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');window.scrollTo(0,0)}
function setupEvents(){$('.menu-toggle').addEventListener('click',e=>{const open=$('.site-nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});window.addEventListener('hashchange',route);$('#daily-language').addEventListener('change',()=>updateTranslation('#daily-language','#daily-translation'));$('#reader-language').addEventListener('change',renderChapter);$('#book-select').addEventListener('change',e=>{currentBook=e.target.value;currentChapter=1;highlightRef='';populateChapters();renderChapter()});$('#chapter-select').addEventListener('change',e=>{currentChapter=Number(e.target.value);highlightRef='';renderChapter()});$('#previous-chapter').addEventListener('click',()=>changeChapter(-1));$('#next-chapter').addEventListener('click',()=>changeChapter(1));$('#read-daily-chapter').addEventListener('click',()=>openReference(dailyRef));$$('[data-ref]').forEach(a=>a.addEventListener('click',()=>openReference(a.dataset.ref)));$('#email-soap').addEventListener('click',()=>{$('#soap-status').textContent='Email delivery will be activated when the church email service is connected. Your writing remains in this browser.'});$('#save-soap').addEventListener('click',()=>{$('#soap-status').textContent='Account storage will be activated when secure subscriptions are connected. Your writing remains in this browser.'});$('#donate-button').addEventListener('click',()=>alert('Secure donations are not active yet. No payment information has been collected.'));['soap-observation','soap-application','soap-prayer'].forEach(id=>{const field=document.getElementById(id);field.value=sessionStorage.getItem(id)||'';field.addEventListener('input',()=>sessionStorage.setItem(id,field.value))})}
async function init(){populateLanguages();populateBooks();setupEvents();try{const response=await fetch('assets/kjv-1769.json');if(!response.ok)throw new Error('Bible data unavailable');bibleData=await response.json()}catch(error){console.error(error)}updateDaily();renderChapter();route();$('#year').textContent=new Date().getFullYear()}
init();
