const BOOKS={Genesis:50,Exodus:40,Leviticus:27,Numbers:36,Deuteronomy:34,Joshua:24,Judges:21,Ruth:4,'1 Samuel':31,'2 Samuel':24,'1 Kings':22,'2 Kings':25,'1 Chronicles':29,'2 Chronicles':36,Ezra:10,Nehemiah:13,Esther:10,Job:42,Psalms:150,Proverbs:31,Ecclesiastes:12,'Song of Solomon':8,Isaiah:66,Jeremiah:52,Lamentations:5,Ezekiel:48,Daniel:12,Hosea:14,Joel:3,Amos:9,Obadiah:1,Jonah:4,Micah:7,Nahum:3,Habakkuk:3,Zephaniah:3,Haggai:2,Zechariah:14,Malachi:4,Matthew:28,Mark:16,Luke:24,John:21,Acts:28,Romans:16,'1 Corinthians':16,'2 Corinthians':13,Galatians:6,Ephesians:6,Philippians:4,Colossians:4,'1 Thessalonians':5,'2 Thessalonians':3,'1 Timothy':6,'2 Timothy':4,Titus:3,Philemon:1,Hebrews:13,James:5,'1 Peter':5,'2 Peter':3,'1 John':5,'2 John':1,'3 John':1,Jude:1,Revelation:22};
const LANG={en:'English',tl:'Tagalog / Filipino',ceb:'Cebuano',hil:'Hiligaynon',es:'Spanish','zh-CN':'Chinese (Simplified)'};
const DAY=['Psalms 118:24','Joshua 1:8','Isaiah 40:31','Matthew 11:28','John 3:16','Romans 8:28','Philippians 4:13','Psalms 46:1','Proverbs 3:5','Hebrews 4:9','Mark 2:28','2 Corinthians 5:17','Revelation 14:12','Psalms 119:105'];
const NIGHT=['Psalms 4:8','Psalms 63:6','Psalms 91:1','Psalms 121:4','Psalms 139:12','Proverbs 3:24','Isaiah 26:9','Lamentations 2:19','Matthew 14:23','Mark 13:35','Luke 6:12','Acts 16:25','1 Thessalonians 5:5','Psalms 119:148'];
const EVENTS={passover:{name:'Passover',day:'1 Corinthians 5:7',night:'Exodus 12:13',theme:'Christ our Passover and deliverance through His blood'},unleavened:{name:'Feast of Unleavened Bread',day:'1 Corinthians 5:8',night:'Exodus 12:17',theme:'sincerity, truth and a cleansed walk in Christ'},firstfruits:{name:'Firstfruits',day:'1 Corinthians 15:20',night:'Matthew 28:6',theme:'the resurrection of the Lord Jesus Christ'},pentecost:{name:'Pentecost',day:'Acts 2:4',night:'John 14:16',theme:'the promised Holy Ghost and witness for Christ'},trumpets:{name:'Feast of Trumpets',day:'1 Thessalonians 4:16',night:'Matthew 25:6',theme:'watchfulness and the return of the Lord Jesus Christ'},atonement:{name:'Day of Atonement',day:'Hebrews 9:28',night:'Hebrews 4:14',theme:'Christ our sacrifice and great High Priest'},tabernacles:{name:'Feast of Tabernacles',day:'John 1:14',night:'Revelation 21:3',theme:'God dwelling with His people through Jesus Christ'},eighth:{name:'The Eighth Day',day:'John 7:37',night:'Revelation 22:17',theme:'the Lord Jesus Christ satisfying the spiritually thirsty'},sabbath:{name:'Seventh-Day Sabbath',day:'Mark 2:28',night:'Hebrews 4:9',theme:'holy rest and the Lord Jesus Christ, Lord of the Sabbath'}};
const COMMANDMENTS=[['I','No other gods','Thou shalt have no other gods before me.','Exodus 20:3'],['II','No graven images','Thou shalt not make unto thee any graven image… Thou shalt not bow down thyself to them, nor serve them…','Exodus 20:4–5'],['III','Honour God’s name','Thou shalt not take the name of the LORD thy God in vain…','Exodus 20:7'],['IV','Remember the Sabbath','Remember the sabbath day, to keep it holy. Six days shalt thou labour, and do all thy work: But the seventh day is the sabbath of the LORD thy God…','Exodus 20:8–10'],['V','Honour father and mother','Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee.','Exodus 20:12'],['VI','Do not kill','Thou shalt not kill.','Exodus 20:13'],['VII','Do not commit adultery','Thou shalt not commit adultery.','Exodus 20:14'],['VIII','Do not steal','Thou shalt not steal.','Exodus 20:15'],['IX','Do not bear false witness','Thou shalt not bear false witness against thy neighbour.','Exodus 20:16'],['X','Do not covet','Thou shalt not covet… any thing that is thy neighbour’s.','Exodus 20:17']];
const FEASTS=[['Passover','Deliverance through the blood of the lamb, fulfilled in Christ our passover.','Leviticus 23:5 · 1 Corinthians 5:7'],['Unleavened Bread','Seven days remembering deliverance and the call to sincerity and truth.','Leviticus 23:6–8'],['Firstfruits','The first sheaf, pointing to Christ risen from the dead.','Leviticus 23:9–14 · 1 Corinthians 15:20'],['Pentecost','The Feast of Weeks and a proclaimed holy convocation.','Leviticus 23:15–21 · Acts 2'],['Trumpets','A memorial of blowing of trumpets, an holy convocation.','Leviticus 23:23–25'],['Day of Atonement','A solemn day of affliction, holy convocation and sabbath of rest.','Leviticus 23:26–32'],['Tabernacles','Seven days of rejoicing before the LORD.','Leviticus 23:33–43'],['The Eighth Day','A distinct holy convocation and solemn assembly.','Leviticus 23:36, 39']];
const HYMNS=[{title:'Holy, Holy, Holy',theme:'christ feast',ref:'Revelation 4:8',lyrics:'Holy, holy, holy! Lord God Almighty!\nEarly in the morning our song shall rise to Thee;\nHoly, holy, holy! Merciful and mighty!\nGod in three Persons, blessed Trinity!'},{title:'Jesus Paid It All',theme:'christ feast',ref:'Isaiah 1:18',lyrics:'I hear the Saviour say, Thy strength indeed is small;\nChild of weakness, watch and pray, find in Me thine all in all.\nJesus paid it all, all to Him I owe;\nSin had left a crimson stain, He washed it white as snow.'},{title:'Come, Thou Fount of Every Blessing',theme:'prayer christ',ref:'1 Samuel 7:12',lyrics:'Come, Thou Fount of every blessing, tune my heart to sing Thy grace;\nStreams of mercy, never ceasing, call for songs of loudest praise.'},{title:'All Hail the Power of Jesus’ Name',theme:'christ',ref:'Philippians 2:10–11',lyrics:'All hail the power of Jesus’ name! Let angels prostrate fall;\nBring forth the royal diadem, and crown Him Lord of all.'},{title:'O Day of Rest and Gladness',theme:'sabbath',ref:'Exodus 20:8',lyrics:'O day of rest and gladness, O day of joy and light,\nO balm of care and sadness, most beautiful, most bright.'},{title:'Rock of Ages',theme:'christ prayer feast',ref:'1 Corinthians 10:4',lyrics:'Rock of Ages, cleft for me, let me hide myself in Thee;\nLet the water and the blood, from Thy wounded side which flowed,\nBe of sin the double cure, save from wrath and make me pure.'}];
const DEVOTIONAL_WEEKS=[
[{type:'Morning',theme:'Faith',title:'Trust the LORD Today',ref:'Proverbs 3:5–6',context:'Solomon calls God’s people away from self-reliance and toward wholehearted trust.',exposition:'Faith acknowledges the LORD in every path. The Lord Jesus Christ is the wisdom and sure foundation upon whom we may safely depend.',application:'Name one decision you will deliberately entrust to the LORD today.',questions:'Where am I leaning upon my own understanding? How can I acknowledge Christ in this decision?',prayer:'Lord Jesus, direct my paths and teach me to trust Thee with all my heart.'},{type:'Evening',theme:'Prayer',title:'Resting in God’s Keeping',ref:'Psalms 4:8',context:'David could lie down in peace because his safety rested in the LORD.',exposition:'Night removes our illusion of control. Christ invites the weary to entrust body, family and future to His keeping.',application:'Release today’s unfinished burdens to the LORD before sleeping.',questions:'What anxiety am I still carrying? What evidence of God’s faithfulness did I see today?',prayer:'LORD, give me peaceful rest and keep me safely through the night.'},{type:'Biblical Calendar',theme:'Obedience',title:'Hear and Do',ref:'James 1:22–25',context:'James warns against hearing Scripture without obeying it.',exposition:'The Word reveals our true condition. The Lord Jesus calls us not merely to admire truth but to continue in it as obedient disciples.',application:'Act upon one clear command of Scripture today.',questions:'What truth have I heard but delayed obeying?',prayer:'Lord Jesus, make me a doer of Thy Word.'}],
[{type:'Morning',theme:'Hope',title:'New Mercies This Morning',ref:'Lamentations 3:22–24',context:'Jeremiah confessed God’s faithfulness in the middle of affliction.',exposition:'Our hope does not rest in easy circumstances but in the LORD’s unchanging compassions. In Christ, mercy meets guilty sinners.',application:'Begin the day by naming three mercies from God.',questions:'Have circumstances become larger in my sight than God’s faithfulness?',prayer:'LORD, thank Thee for new mercies and an unfailing portion.'},{type:'Evening',theme:'Prayer',title:'Search Me, O God',ref:'Psalms 139:23–24',context:'David invited the all-knowing God to examine his inner life.',exposition:'Honest evening examination is not despair; it is an invitation for God to expose harmful ways and lead us through Christ in the everlasting way.',application:'Confess specifically rather than generally.',questions:'Which thought, word or action today needs confession or correction?',prayer:'Search me, O God, and lead me in the way everlasting.'},{type:'Biblical Calendar',theme:'Stewardship',title:'Faithful in That Which Is Least',ref:'Luke 16:10–13',context:'Jesus joined faithfulness in small matters to the heart’s true master.',exposition:'Money is a servant and a test, never a lord. Christ alone deserves worship; every resource should be handled under His authority.',application:'Review one financial habit and bring it under biblical stewardship.',questions:'Does my spending reveal service to God or to mammon?',prayer:'Lord Jesus, make me faithful with every resource entrusted to me.'}],
[{type:'Morning',theme:'Obedience',title:'Strength for the Work',ref:'Philippians 4:13',context:'Paul learned contentment in both want and abundance through Christ.',exposition:'This promise is not permission for self-glory. It is confidence that Christ strengthens His servant to remain faithful in every condition.',application:'Approach today’s difficult duty through dependence on Christ.',questions:'Am I seeking strength for obedience or merely for personal ambition?',prayer:'Lord Jesus, strengthen me to do Thy will faithfully.'},{type:'Evening',theme:'Hope',title:'The Keeper of Israel',ref:'Psalms 121:3–8',context:'The pilgrim’s help comes from the LORD who made heaven and earth.',exposition:'Human strength sleeps, but the Keeper of Israel neither slumbers nor sleeps. Christ watches over His people in every going out and coming in.',application:'Turn fear of tomorrow into thanksgiving for God’s keeping.',questions:'Where did the LORD preserve or redirect me today?',prayer:'LORD, preserve my going out and coming in.'},{type:'Biblical Calendar',theme:'Family',title:'Teach Them Diligently',ref:'Deuteronomy 6:4–9',context:'Israel was commanded to love God wholly and teach His words continually.',exposition:'Biblical discipleship belongs in ordinary home life. The words of God should shape conversation, habits and decisions, pointing every generation to Christ.',application:'Share one KJV passage with your household.',questions:'What truth does my family need to hear and see practised?',prayer:'LORD, help our household love Thee and keep Thy Word before us.'}],
[{type:'Morning',theme:'Prayer',title:'Ask in Faith',ref:'James 1:5–6',context:'God promises wisdom to those who ask Him without wavering.',exposition:'Wisdom begins with humble dependence. Through Christ we may come to God and ask for direction rather than trusting impulse.',application:'Pause and pray for wisdom before the day’s major decision.',questions:'Have I asked God, or merely asked others?',prayer:'LORD, give me wisdom and establish my heart in faith.'},{type:'Evening',theme:'Faith',title:'Remember His Benefits',ref:'Psalms 103:1–5',context:'David commanded his own soul not to forget the LORD’s benefits.',exposition:'Gratitude must often be intentional. Every forgiveness, healing mercy and provision directs praise to God, whose greatest gift is salvation in Christ.',application:'Record the LORD’s benefits from this day.',questions:'Which mercy did I overlook because it seemed ordinary?',prayer:'Bless the LORD, O my soul, and forget not all His benefits.'},{type:'Biblical Calendar',theme:'Obedience',title:'Walk in the Light',ref:'1 John 1:7–9',context:'John connects fellowship with God to walking in His light and confessing sin.',exposition:'We do not cleanse ourselves by hiding. The blood of Jesus Christ cleanseth from all sin, calling us into honest confession and obedient fellowship.',application:'Bring hidden sin into God’s light and forsake it.',questions:'What am I tempted to conceal from God or excuse?',prayer:'Lord Jesus, cleanse me and help me walk in Thy light.'}],
[{type:'Morning',theme:'Faith',title:'Seek First the Kingdom',ref:'Matthew 6:31–34',context:'Jesus addressed anxious hearts concerned about daily necessities.',exposition:'Our heavenly Father knows every need. Seeking Christ’s kingdom first rearranges priorities and refuses to let tomorrow’s imagined trouble rule today.',application:'Put one kingdom responsibility before a lesser anxiety.',questions:'What tomorrow-trouble is stealing today’s obedience?',prayer:'Father, help me seek Thy kingdom and trust Thy provision.'},{type:'Evening',theme:'Prayer',title:'A Sacrifice of Thanksgiving',ref:'Psalms 116:12–17',context:'The psalmist answered deliverance with thanksgiving and fulfilled vows.',exposition:'We cannot repay the LORD, but we can receive His salvation, call upon Him and give thanks. Christ is the ground of our grateful worship.',application:'Thank God aloud for a specific answered prayer.',questions:'Have I remembered to thank the LORD after asking for help?',prayer:'LORD, I will call upon Thy name and offer thanksgiving.'},{type:'Biblical Calendar',theme:'Stewardship',title:'The Diligent Hand',ref:'Proverbs 10:4–5',context:'Proverbs contrasts sloth with diligent and timely labour.',exposition:'Godly increase ordinarily involves honest, disciplined work. Wealth must never become an idol; diligence is stewardship under the Lordship of Christ.',application:'Complete one important task you have been postponing.',questions:'Where has delay weakened my stewardship?',prayer:'LORD, establish the work of my hands in honesty and diligence.'}],
[{type:'Morning',theme:'Sabbath',title:'Prepare for Holy Time',ref:'Exodus 16:22–30',context:'Israel gathered and prepared before the seventh-day Sabbath.',exposition:'Preparation guards holy time from avoidable distraction. Christ, Lord of the Sabbath, calls His people to receive God’s gift with trust and obedience.',application:'Finish ordinary preparations so the Sabbath may be set apart.',questions:'What can I prepare now to protect tomorrow’s worship and rest?',prayer:'Lord of the Sabbath, prepare my heart to delight in Thy holy day.'},{type:'Evening',theme:'Sabbath',title:'From Evening Unto Evening',ref:'Leviticus 23:32',context:'God described the solemn sabbath as observed from evening unto evening.',exposition:'Sunset teaches that sacred time is received from God rather than invented by man. Enter it with repentance, peace and faith in Christ.',application:'Lay aside ordinary business and welcome holy time prayerfully.',questions:'What worldly concern must I release as holy time begins?',prayer:'LORD, turn my heart from distraction unto worship.'},{type:'Biblical Calendar',theme:'Sabbath',title:'Lord Also of the Sabbath',ref:'Mark 2:27–28',context:'Jesus corrected burdensome traditions and declared His authority over the Sabbath.',exposition:'The Sabbath was made for man, and the Son of man is its Lord. True observance honours Christ through worship, mercy, rest and obedience.',application:'Plan worship, Scripture, mercy and fellowship for the Sabbath.',questions:'Does my Sabbath practice centre upon the Lord Jesus Christ?',prayer:'Lord Jesus, teach me to honour Thee as Lord of the Sabbath.'}],
[{type:'Morning',theme:'Sabbath',title:'Call the Sabbath a Delight',ref:'Isaiah 58:13–14',context:'Isaiah joins Sabbath delight with turning from self-directed pursuits.',exposition:'Holy time is not empty restriction but delight in the LORD. Christ is more satisfying than ordinary pleasures or business.',application:'Choose worship and mercy that make the Sabbath a delight.',questions:'What competes with delighting in the LORD today?',prayer:'LORD, cause me to delight myself in Thee.'},{type:'Evening',theme:'Hope',title:'Come Unto Me and Rest',ref:'Matthew 11:28–30',context:'Jesus invites the labouring and heavy laden to come directly unto Him.',exposition:'Physical rest cannot cure the burden of sin. Christ gives rest to the soul and teaches His disciples to bear His easy yoke.',application:'Bring your heaviest burden to Jesus in prayer.',questions:'Am I merely pausing work, or truly coming to Christ?',prayer:'Lord Jesus, give rest unto my soul and teach me Thy way.'},{type:'Biblical Calendar',theme:'Sabbath',title:'There Remaineth a Rest',ref:'Hebrews 4:9–11',context:'Hebrews uses God’s rest to call His people to faith and persevering obedience.',exposition:'The Sabbath points beyond itself to rest in God’s completed work. Through Christ we cease trying to save ourselves and labour to enter by faith.',application:'Rest in Christ’s finished work while remaining diligent in obedience.',questions:'Where am I attempting to earn what Christ freely gives?',prayer:'Lord Jesus, keep me in faithful rest and obedient hope.'}]
];
const FULL_HYMN_LYRICS={
'Holy, Holy, Holy':`1. Holy, holy, holy! Lord God Almighty!\nEarly in the morning our song shall rise to Thee;\nHoly, holy, holy! Merciful and mighty!\nGod in three Persons, blessed Trinity!\n\n2. Holy, holy, holy! All the saints adore Thee,\nCasting down their golden crowns around the glassy sea;\nCherubim and seraphim falling down before Thee,\nWhich wert, and art, and evermore shalt be.\n\n3. Holy, holy, holy! Though the darkness hide Thee,\nThough the eye of sinful man Thy glory may not see,\nOnly Thou art holy; there is none beside Thee,\nPerfect in power, in love, and purity.\n\n4. Holy, holy, holy! Lord God Almighty!\nAll Thy works shall praise Thy name, in earth, and sky, and sea;\nHoly, holy, holy! Merciful and mighty!\nGod in three Persons, blessed Trinity!`,
'Jesus Paid It All':`1. I hear the Saviour say, Thy strength indeed is small;\nChild of weakness, watch and pray, find in Me thine all in all.\n\nRefrain:\nJesus paid it all, all to Him I owe;\nSin had left a crimson stain, He washed it white as snow.\n\n2. Lord, now indeed I find Thy power, and Thine alone,\nCan change the leper's spots, and melt the heart of stone.\n\n3. For nothing good have I whereby Thy grace to claim—\nI'll wash my garments white in the blood of Calvary's Lamb.\n\n4. And when, before the throne, I stand in Him complete,\nJesus died my soul to save, my lips shall still repeat.`,
'Come, Thou Fount of Every Blessing':`1. Come, Thou Fount of every blessing, tune my heart to sing Thy grace;\nStreams of mercy, never ceasing, call for songs of loudest praise.\nTeach me some melodious sonnet, sung by flaming tongues above.\nPraise the mount! I'm fixed upon it, mount of Thy redeeming love.\n\n2. Here I raise mine Ebenezer; hither by Thy help I'm come;\nAnd I hope, by Thy good pleasure, safely to arrive at home.\nJesus sought me when a stranger, wandering from the fold of God;\nHe, to rescue me from danger, interposed His precious blood.\n\n3. O to grace how great a debtor daily I'm constrained to be!\nLet Thy goodness, like a fetter, bind my wandering heart to Thee.\nProne to wander, Lord, I feel it, prone to leave the God I love;\nHere's my heart, O take and seal it, seal it for Thy courts above.`,
'All Hail the Power of Jesus’ Name':`1. All hail the power of Jesus' name! Let angels prostrate fall;\nBring forth the royal diadem, and crown Him Lord of all.\n\n2. Crown Him, ye martyrs of your God, who from His altar call;\nExtol the Stem of Jesse's rod, and crown Him Lord of all.\n\n3. Ye seed of Israel's chosen race, ye ransomed from the fall,\nHail Him who saves you by His grace, and crown Him Lord of all.\n\n4. Sinners, whose love can ne'er forget the wormwood and the gall,\nGo, spread your trophies at His feet, and crown Him Lord of all.\n\n5. Let every kindred, every tribe, on this terrestrial ball,\nTo Him all majesty ascribe, and crown Him Lord of all.\n\n6. O that with yonder sacred throng we at His feet may fall!\nWe'll join the everlasting song, and crown Him Lord of all.`,
'O Day of Rest and Gladness':`1. O day of rest and gladness, O day of joy and light,\nO balm of care and sadness, most beautiful, most bright;\nOn thee, the high and lowly, through ages joined in tune,\nSing holy, holy, holy, to the great God Triune.\n\n2. On thee, at the creation, the light first had its birth;\nOn thee, for our salvation, Christ rose from depths of earth;\nOn thee, our Lord victorious, the Spirit sent from heaven;\nAnd thus on thee, most glorious, a triple light was given.\n\n3. Thou art a cooling fountain in life's dry, dreary sand;\nFrom thee, like Pisgah's mountain, we view our promised land;\nA day of sweet refection, a day of holy love,\nA day of resurrection from earth to things above.\n\n4. Today on weary nations the heavenly manna falls;\nTo holy convocations the silver trumpet calls,\nWhere gospel light is glowing with pure and radiant beams,\nAnd living water flowing with soul-refreshing streams.`,
'Rock of Ages':`1. Rock of Ages, cleft for me, let me hide myself in Thee;\nLet the water and the blood, from Thy wounded side which flowed,\nBe of sin the double cure, save from wrath and make me pure.\n\n2. Not the labours of my hands can fulfil Thy law's demands;\nCould my zeal no respite know, could my tears forever flow,\nAll for sin could not atone; Thou must save, and Thou alone.\n\n3. Nothing in my hand I bring, simply to Thy cross I cling;\nNaked, come to Thee for dress; helpless, look to Thee for grace;\nFoul, I to the fountain fly; wash me, Saviour, or I die.\n\n4. While I draw this fleeting breath, when mine eyes shall close in death,\nWhen I soar to worlds unknown, see Thee on Thy judgment throne,\nRock of Ages, cleft for me, let me hide myself in Thee.`};
HYMNS.push(
{title:'Amazing Grace',theme:'christ prayer hope',ref:'Ephesians 2:8–9',lyrics:`1. Amazing grace! how sweet the sound, that saved a wretch like me!\nI once was lost, but now am found, was blind, but now I see.\n\n2. 'Twas grace that taught my heart to fear, and grace my fears relieved;\nHow precious did that grace appear the hour I first believed!\n\n3. Through many dangers, toils and snares, I have already come;\n'Tis grace hath brought me safe thus far, and grace will lead me home.\n\n4. The Lord has promised good to me, His word my hope secures;\nHe will my shield and portion be, as long as life endures.\n\n5. Yes, when this flesh and heart shall fail, and mortal life shall cease,\nI shall possess, within the veil, a life of joy and peace.\n\n6. The earth shall soon dissolve like snow, the sun forbear to shine;\nBut God, who called me here below, will be forever mine.`},
{title:'What a Friend We Have in Jesus',theme:'christ prayer',ref:'Hebrews 4:15–16',lyrics:`1. What a Friend we have in Jesus, all our sins and griefs to bear!\nWhat a privilege to carry everything to God in prayer!\nO what peace we often forfeit, O what needless pain we bear,\nAll because we do not carry everything to God in prayer!\n\n2. Have we trials and temptations? Is there trouble anywhere?\nWe should never be discouraged; take it to the Lord in prayer.\nCan we find a friend so faithful who will all our sorrows share?\nJesus knows our every weakness; take it to the Lord in prayer.\n\n3. Are we weak and heavy laden, cumbered with a load of care?\nPrecious Saviour, still our refuge; take it to the Lord in prayer.\nDo thy friends despise, forsake thee? Take it to the Lord in prayer!\nIn His arms He'll take and shield thee; thou wilt find a solace there.`},
{title:'Nearer, My God, to Thee',theme:'prayer hope',ref:'Genesis 28:10–17',lyrics:`1. Nearer, my God, to Thee, nearer to Thee!\nE'en though it be a cross that raiseth me,\nStill all my song shall be, nearer, my God, to Thee;\nNearer, my God, to Thee, nearer to Thee!\n\n2. Though like the wanderer, the sun gone down,\nDarkness be over me, my rest a stone;\nYet in my dreams I'd be nearer, my God, to Thee;\nNearer, my God, to Thee, nearer to Thee!\n\n3. There let the way appear, steps unto heaven;\nAll that Thou sendest me, in mercy given;\nAngels to beckon me nearer, my God, to Thee;\nNearer, my God, to Thee, nearer to Thee!\n\n4. Then, with my waking thoughts bright with Thy praise,\nOut of my stony griefs Bethel I'll raise;\nSo by my woes to be nearer, my God, to Thee;\nNearer, my God, to Thee, nearer to Thee!\n\n5. Or if, on joyful wing cleaving the sky,\nSun, moon, and stars forgot, upward I fly,\nStill all my song shall be, nearer, my God, to Thee;\nNearer, my God, to Thee, nearer to Thee!`},
{title:'How Firm a Foundation',theme:'faith hope christ',ref:'Isaiah 41:10',lyrics:`1. How firm a foundation, ye saints of the Lord,\nIs laid for your faith in His excellent Word!\nWhat more can He say than to you He hath said,\nTo you who for refuge to Jesus have fled?\n\n2. Fear not, I am with thee; O be not dismayed,\nFor I am thy God, and will still give thee aid;\nI'll strengthen thee, help thee, and cause thee to stand,\nUpheld by My righteous, omnipotent hand.\n\n3. When through the deep waters I call thee to go,\nThe rivers of sorrow shall not overflow;\nFor I will be with thee, thy troubles to bless,\nAnd sanctify to thee thy deepest distress.\n\n4. When through fiery trials thy pathway shall lie,\nMy grace, all sufficient, shall be thy supply;\nThe flame shall not hurt thee; I only design\nThy dross to consume, and thy gold to refine.\n\n5. The soul that on Jesus hath leaned for repose,\nI will not, I will not desert to his foes;\nThat soul, though all hell should endeavour to shake,\nI'll never, no, never, no, never forsake!`}
);
HYMNS.forEach(h=>h.lyrics=FULL_HYMN_LYRICS[h.title]||h.lyrics);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let bible={},book='Genesis',chapter=1,verse=1,mode='single',today={},devotionalDate=new Date(),highlightEnd=1,PD_HYMN_CATALOG=[];
const ORIGINAL_TEXT=new WeakMap(),ORIGINAL_PLACEHOLDER=new WeakMap();
const clean=s=>(s||'').replace(/^#\s*/,'').replace(/\[([^\]]+)\]/g,'$1').trim();
const refText=(b=book,c=chapter,v=verse)=>`${b} ${c}:${v}`;

function eventFor(date){let p={};try{p=Object.fromEntries(new Intl.DateTimeFormat('en-u-ca-hebrew',{month:'long',day:'numeric'}).formatToParts(date).filter(x=>x.type==='month'||x.type==='day').map(x=>[x.type,x.value]));}catch{}const m=p.month,d=+p.day;if(m==='Nisan'&&d===14)return EVENTS.passover;if(m==='Nisan'&&d===16)return EVENTS.firstfruits;if(m==='Nisan'&&d>=15&&d<=21)return EVENTS.unleavened;if(m==='Sivan'&&d===6)return EVENTS.pentecost;if((m==='Tishri'||m==='Tishrei')&&d===1)return EVENTS.trumpets;if((m==='Tishri'||m==='Tishrei')&&d===10)return EVENTS.atonement;if((m==='Tishri'||m==='Tishrei')&&d>=15&&d<=21)return EVENTS.tabernacles;if((m==='Tishri'||m==='Tishrei')&&d===22)return EVENTS.eighth;if(date.getDay()===6)return EVENTS.sabbath;return null}
function dailyPair(){const n=new Date(),start=new Date(n.getFullYear(),0,0),index=Math.floor((n-start)/86400000),event=eventFor(n);return{date:n,event,day:event?.day||DAY[index%DAY.length],night:event?.night||NIGHT[index%NIGHT.length]}}
function dateLabel(d){return d.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function soapMarkup(kind,title,ref){const id=kind.toLowerCase();return `<section class="daily pad" id="${id}-section"><header class="section-head"><p class="eyebrow">Daily Bread · ${kind}</p><h2>${title}</h2><p class="date">${dateLabel(today.date)}</p></header><div class="parallel verse-pair"><article class="kjv"><h3>English · King James Version</h3><blockquote id="${id}-en" class="notranslate" translate="no">Loading Scripture…</blockquote><cite id="${id}-ref">${ref} KJV</cite></article><article><h3 id="${id}-lang">Selected language</h3><blockquote id="${id}-tr">Choose a language above. English KJV always remains beside its translation.</blockquote></article></div><div class="soap"><aside><p class="soap-letter">S</p><h3>Scripture</h3><p>Read ${ref} slowly. How does it reveal the Lord Jesus Christ?</p><p class="soap-letter">O</p><h3>Observation</h3><p>What does this verse reveal about God, His will and the condition of man?</p><p class="soap-letter">A</p><h3>Application</h3><p>What truth should I believe, obey or practise ${kind==='Day'?'today':'tonight'}?</p><p class="soap-letter">P</p><h3>Prayer</h3><p>Respond honestly to the LORD through faith in Jesus Christ.</p></aside><form data-soap="${id}"><label>Email address<input name="email" type="email" required placeholder="you@example.com"></label><label>My Observation<textarea name="observation" rows="4"></textarea></label><label>My Application<textarea name="application" rows="4"></textarea></label><label>My Prayer<textarea name="prayer" rows="4"></textarea></label><p class="status" role="status"></p><div class="soap-buttons"><button class="btn navy email-soap" type="button">Email Saved SOAP to Your Email — Free</button><button class="btn outline save-account" type="button">Save to Account — US$1/month</button><a class="btn link" href="#give">Donate to Help Keep This Ministry Online</a></div></form></div></section>`}

async function translate(text,lang){if(lang==='en'||!text)return text;const key=`lotstr:${lang}:${text}`;try{const cached=localStorage.getItem(key);if(cached)return cached}catch{}const url=`https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=${encodeURIComponent(lang)}&dt=t&q=${encodeURIComponent(text)}`;try{const r=await fetch(url);if(!r.ok)throw Error();const data=await r.json(),out=(data[0]||[]).map(x=>x[0]||'').join('');if(!out)throw Error();try{localStorage.setItem(key,out)}catch{}return out}catch{return 'Translation is temporarily unavailable. The English KJV remains available.'}}
async function translateInto(source,target,lang){const el=$(target);if(!el)return;el.textContent=lang==='en'?'English is shown in the KJV panel.':'Translating the exact KJV text…';el.textContent=await translate($(source)?.textContent||'',lang)}
async function translateInterface(lang){const nodes=[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue.trim()||n.parentElement?.closest('.notranslate,[id$="-tr"],#chapter-tr,script,style,textarea,option'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});let node;while(node=walker.nextNode()){if(!ORIGINAL_TEXT.has(node))ORIGINAL_TEXT.set(node,node.nodeValue);nodes.push(node)}const attrs=$$('input[placeholder],textarea[placeholder]');attrs.forEach(e=>{if(!ORIGINAL_PLACEHOLDER.has(e))ORIGINAL_PLACEHOLDER.set(e,e.placeholder)});if(lang==='en'){nodes.forEach(n=>n.nodeValue=ORIGINAL_TEXT.get(n));attrs.forEach(e=>e.placeholder=ORIGINAL_PLACEHOLDER.get(e));return}await Promise.all(nodes.map(async n=>{const original=ORIGINAL_TEXT.get(n),left=original.match(/^\s*/)[0],right=original.match(/\s*$/)[0];n.nodeValue=left+await translate(original.trim(),lang)+right}));await Promise.all(attrs.map(async e=>e.placeholder=await translate(ORIGINAL_PLACEHOLDER.get(e),lang)))}
async function applyInterfaceLanguage(lang){
 document.documentElement.lang=lang==='en'?'en':lang;
 try{localStorage.setItem('lots-language',lang)}catch{}
 /* Translate normal interface/content (including Home hero and SOAP instructions).
    KJV source panels stay English because they are marked .notranslate. */
 await translateInterface(lang);
 await refreshTranslations(lang);
}
async function refreshTranslations(lang){const name=LANG[lang];['day','night','motto','reader'].forEach(k=>{const e=$(`#${k}-lang`);if(e)e.textContent=lang==='en'?'English':`${name} · translated from KJV`});await Promise.all([translateInto('#day-en','#day-tr',lang),translateInto('#night-en','#night-tr',lang),translateInto('#motto-en','#motto-tr',lang),renderReaderTranslation(lang)]);if(mode==='chapter')renderFullChapter(lang);renderHymns()}

function getVerse(b,c,v){return clean((bible&&bible[`${b} ${c}:${v}`])||'')}
function verseCount(b,c){let n=0;while(n<200&&getVerse(b,c,n+1))n++;return n}
function populateBooks(){const s=$('#book-select');Object.keys(BOOKS).forEach(b=>s.add(new Option(b,b)));s.value=book;populateChapters()}
function populateChapters(){const s=$('#chapter-select');s.innerHTML='';for(let i=1;i<=BOOKS[book];i++)s.add(new Option(i,i));s.value=chapter;populateVerses()}
function populateVerses(){const s=$('#verse-select'),n=verseCount(book,chapter)||1;s.innerHTML='';for(let i=1;i<=n;i++)s.add(new Option(i,i));verse=Math.min(verse,n);s.value=verse}
function renderSingle(){mode='single';$('#single-reading').hidden=false;$('#chapter-reading').hidden=true;const ref=refText(),text=getVerse(book,chapter,verse);$('#reader-en').textContent=text?`“${text}”`:'Verse unavailable.';$('#reader-ref').textContent=`${ref} KJV`;$('#reader-tr-ref').textContent=ref;renderReaderTranslation($('#site-language').value);$('#prev-verse').disabled=book==='Genesis'&&chapter===1&&verse===1;$('#next-verse').disabled=book==='Revelation'&&chapter===22&&verse===verseCount(book,chapter)}
async function renderReaderTranslation(lang=$('#site-language').value){$('#reader-tr').textContent=lang==='en'?'English is shown in the KJV panel.':'Translating the exact KJV verse…';$('#reader-tr').textContent=await translate(getVerse(book,chapter,verse),lang)}
function moveVerse(delta){const books=Object.keys(BOOKS);verse+=delta;if(verse<1){if(chapter>1){chapter--;verse=verseCount(book,chapter)}else{let i=books.indexOf(book);if(i===0){verse=1;return}book=books[i-1];chapter=BOOKS[book];verse=verseCount(book,chapter)}}else if(verse>verseCount(book,chapter)){if(chapter<BOOKS[book]){chapter++;verse=1}else{let i=books.indexOf(book);if(i===books.length-1){verse=verseCount(book,chapter);return}book=books[i+1];chapter=1;verse=1}}$('#book-select').value=book;populateChapters();$('#chapter-select').value=chapter;populateVerses();$('#verse-select').value=verse;renderSingle()}
async function renderFullChapter(lang=$('#site-language').value){mode='chapter';$('#single-reading').hidden=true;$('#chapter-reading').hidden=false;const n=verseCount(book,chapter),en=$('#chapter-en'),tr=$('#chapter-tr');$('#chapter-en-title').textContent=`${book} ${chapter} · English KJV`;$('#chapter-tr-title').textContent=`${book} ${chapter} · ${LANG[lang]}`;en.innerHTML='';tr.innerHTML=lang==='en'?'<p>English KJV is displayed beside this panel.</p>':'<p>Translating the exact KJV chapter…</p>';for(let i=1;i<=n;i++){const p=document.createElement('p');p.dataset.v=i;p.className=i===verse?'selected':'';p.innerHTML=`<sup>${i}</sup>${escapeHtml(getVerse(book,chapter,i))}`;en.append(p)}if(lang!=='en'){tr.innerHTML='';for(let start=1;start<=n;start+=12){const end=Math.min(n,start+11),texts=[];for(let i=start;i<=end;i++)texts.push(`[[${i}]] ${getVerse(book,chapter,i)}`);const out=await translate(texts.join('\n'),lang);const blocks=out.split(/\[\[(\d+)\]\]/).slice(1);for(let j=0;j<blocks.length;j+=2){const p=document.createElement('p'),v=+blocks[j];p.className=v===verse?'selected':'';p.innerHTML=`<sup>${v}</sup>${escapeHtml((blocks[j+1]||'').trim())}`;tr.append(p)}}}setTimeout(()=>en.querySelector('.selected')?.scrollIntoView({block:'center'}),20)}
function moveChapter(delta){const books=Object.keys(BOOKS);chapter+=delta;if(chapter<1){const i=books.indexOf(book);if(!i){chapter=1;return}book=books[i-1];chapter=BOOKS[book]}else if(chapter>BOOKS[book]){const i=books.indexOf(book);if(i===books.length-1){chapter=BOOKS[book];return}book=books[i+1];chapter=1}verse=1;$('#book-select').value=book;populateChapters();renderFullChapter()}
const escapeHtml=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function emailSoap(form){const status=form.querySelector('.status'),button=form.querySelector('.email-soap'),kind=form.dataset.soap,email=form.email.value.trim();if(!form.reportValidity())return;if(!form.observation.value.trim()&&!form.application.value.trim()&&!form.prayer.value.trim()){status.textContent='Please write at least one SOAP entry.';return}button.disabled=true;button.textContent='Sending…';const ref=kind==='day'?today.day:today.night;try{const r=await fetch('send-soap.php',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({email,reference:ref,scripture:$(`#${kind}-en`).textContent,observation:form.observation.value,application:form.application.value,prayer:form.prayer.value,website:''})}),data=await r.json().catch(()=>({}));if(!r.ok||!data.success)throw Error(data.message||'Email could not be sent.');status.textContent='Your SOAP journal has been emailed. Please check your inbox and spam folder.'}catch(e){status.textContent=e.message||'Email could not be sent. Please try again.'}finally{button.disabled=false;button.textContent='Email Saved SOAP to Your Email — Free'}}
function preserveSoap(form){['observation','application','prayer'].forEach(n=>{const key=`soap:${form.dataset.soap}:${dateLabel(today.date)}:${n}`,f=form[n];f.value=sessionStorage.getItem(key)||'';f.addEventListener('input',()=>sessionStorage.setItem(key,f.value))})}

function feastFeature(){if(today.event!==EVENTS.atonement)return'';return `<section class="atonement-feature"><div class="atonement-title"><p class="eyebrow">Feast of the LORD · A Holy Convocation</p><h2>Day of Atonement</h2><p class="atonement-date">${dateLabel(today.date)}</p></div><div class="atonement-content"><article><h3>How the LORD commanded it to be observed</h3><p>Leviticus 23:27–32 calls the Day of Atonement a <strong>holy convocation</strong>. God commanded His people to afflict their souls, offer an offering made by fire, do no work, and keep it as a sabbath of rest—from evening unto evening.</p><blockquote>“It shall be unto you a sabbath of rest, and ye shall afflict your souls…” <cite>Leviticus 23:32 KJV</cite></blockquote><p>This is a solemn time for humble self-examination, repentance, prayer, rest from ordinary work, and reverent gathering before the LORD. Fasting may express the biblical command to afflict the soul, but outward observance must be joined with a heart that turns from sin and seeks God sincerely.</p></article><article><h3>Foreshadowing the Lamb of God</h3><p>The sacrifices and high-priestly ministry of the Day of Atonement pointed forward to the perfect and sufficient sacrifice of the Lord Jesus Christ. He did not offer the blood of another; He offered Himself once to bear the sins of many.</p><blockquote>“Behold the Lamb of God, which taketh away the sin of the world.” <cite>John 1:29 KJV</cite></blockquote><p>Hebrews 9 teaches that Christ entered into the holy place by His own blood and obtained eternal redemption. Therefore, this feast directs our faith to His finished atoning work, calls sinners to repentance, and encourages believers to await His appearing.</p><blockquote>“So Christ was once offered to bear the sins of many…” <cite>Hebrews 9:28 KJV</cite></blockquote></article></div><div class="atonement-call"><h3>A solemn invitation</h3><p>Humble your heart before the LORD. Confess and forsake sin. Rest from ordinary labour. Gather for Scripture, prayer and worship. Give thanks that forgiveness and cleansing are found through faith in the Lord Jesus Christ—the Lamb of God and our great High Priest.</p></div></section>`}

async function loadPublicDomainHymnCatalog(){
  try{
    const r=await fetch('hymn-catalog.php?v=20260922-1',{cache:'no-store'}),d=await r.json();
    if(d.ok&&Array.isArray(d.hymns)){PD_HYMN_CATALOG=d.hymns;renderHymns()}
  }catch(e){console.error('Public-domain hymn catalogue',e)}
}
function renderHymns(){
  const q=($('#hymn-search')?.value||'').trim().toLowerCase(),scripture=($('#hymn-scripture')?.value||'').trim().toLowerCase(),f=$('#hymn-filter')?.value||'all',event=today.event;
  let hymns=HYMNS.filter(h=>{const text=`${h.title} ${h.ref} ${h.theme} ${h.lyrics}`.toLowerCase();return(f==='all'||h.theme.includes(f))&&(!q||text.includes(q))&&(!scripture||text.includes(scripture))});
  if(event)hymns.sort((a,b)=>Number(b.theme.includes(event===EVENTS.sabbath?'sabbath':'feast'))-Number(a.theme.includes(event===EVENTS.sabbath?'sabbath':'feast')));
  const catalog=PD_HYMN_CATALOG.filter(h=>{const text=`${h.title} ${h.credit||''}`.toLowerCase();return f==='all'&&(!q||text.includes(q))&&!scripture});
  $('#hymn-season').textContent=event?`Recommended for ${event.name}: ${event.theme}.`:'Public-domain hymn catalogue plus locally stored complete hymns.';
  const status=$('#hymn-search-status');
  if(status)status.textContent=`${hymns.length} complete hymn${hymns.length===1?'':'s'} stored here${PD_HYMN_CATALOG.length?'; '+catalog.length+' additional public-domain catalogue entries available.':'. Loading the full public-domain catalogue…'}`;
  const local=hymns.map(h=>{const i=HYMNS.indexOf(h),passage=hymnScripture(h.ref);return`<button class="hymn-card" type="button" data-hymn-index="${i}" aria-label="Open complete lyrics for ${escapeHtml(h.title)}"><span class="eyebrow">Complete Hymn · Stored Here</span><strong><u>${escapeHtml(h.title)}</u></strong><cite>${escapeHtml(h.ref)} KJV</cite><blockquote class="hymn-scripture-preview notranslate" translate="no">“${escapeHtml(passage)}”</blockquote><span>Click to open all hymn verses →</span></button>`}).join('');
  const remote=catalog.map(h=>`<a class="hymn-card hymn-source-card" href="${escapeHtml(h.source)}" target="_blank" rel="noopener noreferrer"><span class="eyebrow">Public Domain Catalogue</span><strong><u>${escapeHtml(h.title)}</u></strong><cite>${escapeHtml(h.credit||'Hymns To God public-domain list')}</cite><span>Open public-domain hymn source →</span></a>`).join('');
  $('#hymn-list').innerHTML=(local+remote)||'<div class="no-hymns"><h2>No matching hymn found.</h2><p>Try another title or theme.</p></div>';
  $$('.hymn-card[data-hymn-index]').forEach(b=>b.addEventListener('click',()=>openHymnByIndex(Number(b.dataset.hymnIndex))));
}
function openHymnByIndex(index){const h=HYMNS[index];if(h)openHymn(h.title)}
function executeHymnSearch(){renderHymns();$('#hymn-list').scrollIntoView({behavior:'smooth',block:'start'})}
function searchHymnsOnWeb(){const q=$('#hymn-search').value.trim(),s=$('#hymn-scripture').value.trim(),theme=$('#hymn-filter').value==='all'?'':$('#hymn-filter').selectedOptions[0].textContent;const terms=[q,theme,s,'Christian hymn complete lyrics public domain'].filter(Boolean).join(' ');window.open(`https://www.google.com/search?q=${encodeURIComponent(terms)}`,'_blank','noopener,noreferrer')}
function clearHymnSearch(){$('#hymn-search').value='';$('#hymn-scripture').value='';$('#hymn-filter').value='all';renderHymns()}
function hymnScripture(ref){const m=ref.match(/^(.+?)\s(\d+):(\d+)(?:[–-](\d+))?$/);if(!m)return'';const b=m[1],c=Number(m[2]),start=Number(m[3]),end=Number(m[4]||m[3]),parts=[];for(let v=start;v<=end;v++){const text=getVerse(b,c,v);if(text)parts.push(`${v} ${text}`)}return parts.join(' ')}
async function openHymn(title){const h=HYMNS.find(x=>x.title===title);if(!h)return;let modal=$('#hymn-modal');if(!modal){modal=document.createElement('div');modal.id='hymn-modal';modal.className='hymn-modal';document.body.append(modal)}const lang=$('#site-language').value,lyrics=lang==='en'?h.lyrics:await translate(h.lyrics,lang),passage=hymnScripture(h.ref),translatedPassage=lang==='en'?passage:await translate(passage,lang);modal.innerHTML=`<article><button class="hymn-close" aria-label="Close hymn">×</button><p class="eyebrow">Hymn and Spiritual Song · Verified Public Domain</p><h1>${h.title}</h1><section class="hymn-full-scripture"><button class="scripture-link" type="button">${h.ref} KJV</button><blockquote class="notranslate" translate="no">“${escapeHtml(passage)}”</blockquote>${lang==='en'?'':`<blockquote>“${escapeHtml(translatedPassage)}”</blockquote>`}</section><div class="hymn-columns"><pre class="notranslate" translate="no">${escapeHtml(h.lyrics)}</pre>${lang==='en'?'':`<pre>${escapeHtml(lyrics)}</pre>`}</div><p class="translation-disclaimer">${lang==='en'?'Complete verified public-domain English lyrics.':`${LANG[lang]} is an automated translation of the English hymn shown beside it.`}</p></article>`;modal.classList.add('open');document.body.classList.add('modal-open');modal.querySelector('.hymn-close').onclick=closeHymn;modal.querySelector('.scripture-link').onclick=()=>{closeHymn();openDevotionalScripture(h.ref)};modal.onclick=e=>{if(e.target===modal)closeHymn()}}
function closeHymn(){$('#hymn-modal')?.classList.remove('open');document.body.classList.remove('modal-open')}
function route(){const id=location.hash.slice(1)||'home',target=document.getElementById(id);const page=target?.classList.contains('page')?target:$('#home');document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p===page));document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${page.id}`));document.title=`${page.dataset.title} | Lord of the Sabbath Church`;$('#nav').classList.remove('open');if(id==='day-section'||id==='night-section'){requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({block:'start',behavior:'auto'}))}else window.scrollTo(0,0)}
function buildStatic(){today=dailyPair();$('#daily-mount').innerHTML=soapMarkup('Day','Verse of the Day',today.day)+soapMarkup('Night','Verse of the Night',today.night);$('#calendar-title').textContent=today.event?today.event.name:'Daily KJV meditation';$('#calendar-note').textContent=today.event?`Today’s verses, SOAP guidance and hymns emphasize ${today.event.theme}. Day/Night meditation changes at the user's local sunrise and sunset; biblical observances are identified from the biblical calendar.`:'Verse of the Day begins at local sunrise. Verse of the Night begins at local sunset.';$('#commandments-list').innerHTML=COMMANDMENTS.map(x=>`<article><b>${x[0]}</b><h2>${x[1]}</h2><blockquote>“${x[2]}”</blockquote><cite>${x[3]} KJV</cite></article>`).join('');$('#feast-list').innerHTML=FEASTS.map((x,i)=>`<article><b>0${i+1}</b><h2>${x[0]}</h2><p>${x[1]}</p><cite>${x[2]}</cite></article>`).join('');['day','night'].forEach(k=>{const ref=today[k];$(`#${k}-en`).textContent='Loading KJV Scripture…';document.querySelector(`form[data-soap="${k}"] .email-soap`).addEventListener('click',e=>emailSoap(e.target.form));document.querySelector(`form[data-soap="${k}"] .save-account`).addEventListener('click',e=>{e.target.form.querySelector('.status').textContent='Secure account subscriptions require the payment gateway to be connected. Your writing remains safely in this browser for this session.'});preserveSoap(document.querySelector(`form[data-soap="${k}"]`))});renderHymns()}
function parseRef(ref){const m=ref.match(/^(.+?) (\d+):(\d+)$/);return{book:m[1],chapter:+m[2],verse:+m[3]}}
const FINANCE_KEY='lots-finance-v1',TODO_KEY='lots-todos-v1';
let finance={income:[],expenses:[],strategies:[],taxRate:20,period:'Monthly',from:'',to:''},todos=[],todoFilter='Today';
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
function loadPrivateData(){try{finance={...finance,...JSON.parse(localStorage.getItem(FINANCE_KEY)||'{}')};todos=JSON.parse(localStorage.getItem(TODO_KEY)||'[]')}catch{}const now=new Date(),iso=now.toISOString().slice(0,10);$$('#income-form input[type=date],#expense-form input[type=date],#todo-form input[name=start],#todo-form input[name=due]').forEach(e=>e.value=iso);$('#tax-rate').value=finance.taxRate;$('#plan-period').value=finance.period;$('#plan-from').value=finance.from;$('#plan-to').value=finance.to;renderFinance();renderTodos()}
function saveFinance(){localStorage.setItem(FINANCE_KEY,JSON.stringify(finance));renderFinance()}
function money(n){return new Intl.NumberFormat(undefined,{style:'currency',currency:'NZD'}).format(Number(n)||0)}
function addFinanceEntry(type,form){const data=Object.fromEntries(new FormData(form));data.id=uid();data.planned=Number(data.planned)||0;data.actual=Number(data.actual)||0;finance[type].push(data);saveFinance();form.reset();form.date.value=new Date().toISOString().slice(0,10);form.planned.value=form.actual.value=0}
function totals(){const plannedIncome=finance.income.reduce((s,x)=>s+x.planned,0),actualIncome=finance.income.reduce((s,x)=>s+x.actual,0),taxable=finance.income.filter(x=>x.taxable==='yes').reduce((s,x)=>s+x.actual,0),tax=taxable*(finance.taxRate/100),plannedExpenses=finance.expenses.reduce((s,x)=>s+x.planned,0),actualExpenses=finance.expenses.reduce((s,x)=>s+x.actual,0);return{plannedIncome,actualIncome,tax,plannedExpenses,actualExpenses,remaining:actualIncome-tax-actualExpenses}}
function renderFinance(){const t=totals();$('#finance-summary').innerHTML=[['Planned income',t.plannedIncome],['Actual income',t.actualIncome],['Estimated tax',t.tax],['Budgeted expenses',t.plannedExpenses],['Actual expenses',t.actualExpenses],['Remaining',t.remaining]].map(x=>`<article><span>${x[0]}</span><strong class="${x[1]<0?'negative':''}">${money(x[1])}</strong></article>`).join('');$('#income-rows').innerHTML=finance.income.map(x=>`<tr><td>${x.date}</td><td>${escapeHtml(x.category)}</td><td>${escapeHtml(x.description)}</td><td>${money(x.planned)}</td><td>${money(x.actual)}</td><td>${x.taxable}</td><td>${x.status}</td><td><button class="mini-delete" data-finance="income" data-id="${x.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="8">No income entries yet.</td></tr>';$('#expense-rows').innerHTML=finance.expenses.map(x=>`<tr><td>${x.date}</td><td>${escapeHtml(x.category)}</td><td>${escapeHtml(x.description)}</td><td>${money(x.planned)}</td><td>${money(x.actual)}</td><td class="${x.planned-x.actual<0?'negative':''}">${money(x.planned-x.actual)}</td><td>${x.status}</td><td><button class="mini-delete" data-finance="expenses" data-id="${x.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="8">No expense entries yet.</td></tr>';$('#strategy-list').innerHTML=finance.strategies.map(x=>`<article><div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.benefit||'')} · ${x.priority} priority · Target ${x.target||'not set'}</p><p>${escapeHtml(x.notes||'')}</p></div><label>Progress <input class="progress-input" data-id="${x.id}" type="range" min="0" max="100" value="${x.progress}"> <b>${x.progress}%</b></label><button class="mini-delete" data-finance="strategies" data-id="${x.id}">Delete</button></article>`).join('')||'<p>No strategies added yet.</p>';$$('[data-finance]').forEach(b=>b.onclick=()=>{finance[b.dataset.finance]=finance[b.dataset.finance].filter(x=>x.id!==b.dataset.id);saveFinance()});$$('.progress-input').forEach(r=>r.onchange=()=>{const x=finance.strategies.find(s=>s.id===r.dataset.id);x.progress=Number(r.value);if(x.progress===100&&!x.completed)x.completed=new Date().toISOString().slice(0,10);saveFinance()})}
function financeText(){const t=totals();return `MY FINANCIAL PLAN\nPeriod: ${finance.period} ${finance.from||''} to ${finance.to||''}\n\nSUMMARY\nPlanned income: ${money(t.plannedIncome)}\nActual income: ${money(t.actualIncome)}\nEstimated tax: ${money(t.tax)}\nActual expenses: ${money(t.actualExpenses)}\nRemaining: ${money(t.remaining)}\n\nINCOME\n${finance.income.map(x=>`${x.date} | ${x.category} | ${x.description} | ${money(x.actual)}`).join('\n')||'None'}\n\nEXPENSES\n${finance.expenses.map(x=>`${x.date} | ${x.category} | ${x.description} | ${money(x.actual)}`).join('\n')||'None'}\n\nGODLY WEALTH-BUILDING PLAN\n${finance.strategies.map(x=>`${x.title} | ${x.progress}% | target ${x.target||'not set'} | ${x.notes||''}`).join('\n')||'None'}`}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}
function financeCsv(){const rows=[['Type','Date','Category/Strategy','Description','Planned','Actual','Status/Progress']];finance.income.forEach(x=>rows.push(['Income',x.date,x.category,x.description,x.planned,x.actual,x.status]));finance.expenses.forEach(x=>rows.push(['Expense',x.date,x.category,x.description,x.planned,x.actual,x.status]));finance.strategies.forEach(x=>rows.push(['Strategy',x.start,x.title,x.notes,'','',`${x.progress}%`]));return rows.map(r=>r.map(csvCell).join(',')).join('\n')}
async function emailPrivate(kind,body,status){const email=prompt('Enter the email address where you want this sent:');if(!email)return;status.textContent='Sending securely…';try{const r=await fetch('send-planner.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,kind,body,website:''})}),d=await r.json();if(!r.ok||!d.success)throw Error(d.message||'Email could not be sent.');status.textContent='Email sent successfully. Please check your inbox and spam folder.'}catch(e){status.textContent=e.message||'Email could not be sent.'}}
function addStrategy(form){const x=Object.fromEntries(new FormData(form));x.id=uid();x.progress=Number(x.progress)||0;finance.strategies.push(x);saveFinance();form.reset();form.progress.value=0}
function initFinance(){const f1=$('#income-form'),f2=$('#expense-form'),fs=$('#strategy-form');f1.onsubmit=e=>{e.preventDefault();addFinanceEntry('income',f1)};f2.onsubmit=e=>{e.preventDefault();addFinanceEntry('expenses',f2)};fs.onsubmit=e=>{e.preventDefault();addStrategy(fs)};$('#tax-rate').onchange=e=>{finance.taxRate=Number(e.target.value)||0;saveFinance()};$('#plan-period').onchange=e=>{finance.period=e.target.value;saveFinance()};$('#plan-from').onchange=e=>{finance.from=e.target.value;saveFinance()};$('#plan-to').onchange=e=>{finance.to=e.target.value;saveFinance()};$('#email-finance').onclick=()=>emailPrivate('Financial Plan',financeText(),$('#finance-status'));$('#print-finance').onclick=()=>window.print();$('#csv-finance').onclick=()=>download('my-financial-plan.csv',financeCsv(),'text/csv');$('#backup-finance').onclick=()=>download('financial-plan-backup.json',JSON.stringify(finance,null,2),'application/json');$('#restore-finance').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.income)||!Array.isArray(data.expenses))throw Error();finance={...finance,...data};saveFinance();$('#finance-status').textContent='Backup restored.'}catch{$('#finance-status').textContent='This is not a valid financial-plan backup.'}};$('#clear-finance').onclick=()=>{if(confirm('Permanently clear all financial-plan entries from this browser?')){finance={income:[],expenses:[],strategies:[],taxRate:20,period:'Monthly',from:'',to:''};saveFinance()}}}

function saveTodos(){localStorage.setItem(TODO_KEY,JSON.stringify(todos));renderTodos()}
function addTodo(form){const x=Object.fromEntries(new FormData(form));x.id=uid();x.done=false;x.completed='';todos.push(x);saveTodos();form.reset();const d=new Date().toISOString().slice(0,10);form.start.value=form.due.value=d}
function renderTodos(){const todayIso=new Date().toISOString().slice(0,10);let list=todoFilter==='All'?todos:todos.filter(x=>x.period===todoFilter);list=[...list].sort((a,b)=>(a.done-b.done)||a.due.localeCompare(b.due));$('#todo-list').innerHTML=list.map(x=>`<article class="task ${x.done?'done':''} ${!x.done&&x.due<todayIso?'overdue':''}"><div><p><b>${escapeHtml(x.title)}</b> <span>${x.priority}</span></p><p>${escapeHtml(x.category||'')} · Due ${x.due}${x.time?' at '+x.time:''}</p><p>${escapeHtml(x.comments||'')}</p>${x.completed?`<small>Completed ${x.completed}</small>`:''}</div><button class="task-done" data-id="${x.id}">${x.done?'Undo':'Done'}</button><button class="mini-delete" data-task="${x.id}">Delete</button></article>`).join('')||'<p>No tasks in this period.</p>';$$('.task-done').forEach(b=>b.onclick=()=>{const x=todos.find(t=>t.id===b.dataset.id);x.done=!x.done;x.completed=x.done?new Date().toLocaleString():'';saveTodos()});$$('[data-task]').forEach(b=>b.onclick=()=>{todos=todos.filter(x=>x.id!==b.dataset.task);saveTodos()})}
function todosText(){return `MY THINGS TO DO\n\n${todos.map(x=>`${x.done?'DONE':'TO DO'} | ${x.period} | ${x.due} ${x.time||''} | ${x.title} | ${x.comments||''}${x.completed?' | Completed '+x.completed:''}`).join('\n')||'No tasks saved.'}`}
function todosCsv(){const rows=[['Status','Period','Task','Category','Priority','Start','Due','Time','Comments','Completed'],...todos.map(x=>[x.done?'Done':'To Do',x.period,x.title,x.category,x.priority,x.start,x.due,x.time,x.comments,x.completed])];return rows.map(r=>r.map(csvCell).join(',')).join('\n')}
function initTodos(){const f=$('#todo-form');f.onsubmit=e=>{e.preventDefault();addTodo(f)};$$('.task-filter').forEach(b=>b.onclick=()=>{$$('.task-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');todoFilter=b.dataset.period;renderTodos()});$('#email-todos').onclick=()=>emailPrivate('Things to Do',todosText(),$('#todo-status'));$('#print-todos').onclick=()=>window.print();$('#csv-todos').onclick=()=>download('my-things-to-do.csv',todosCsv(),'text/csv');$('#delete-completed').onclick=()=>{if(confirm('Delete all completed tasks?')){todos=todos.filter(x=>!x.done);saveTodos()}};$('#clear-todos').onclick=()=>{if(confirm('Permanently clear every task from this browser?')){todos=[];saveTodos()}}}
function feastDevotional(date){const e=eventFor(date);if(!e)return null;const map={
'Day of Atonement':{theme:'Feasts',title:'The Lamb Who Taketh Away Sin',ref:'Hebrews 9:24–28',context:'The Day of Atonement’s sacrifices and high-priestly ministry pointed beyond themselves to Christ.',exposition:'The Lord Jesus entered the true holy place and was once offered to bear the sins of many. His sacrifice is sufficient; believers await His appearing with repentance, faith and hope.',application:'Humble your soul, confess and forsake sin, and rest your faith wholly upon Christ’s atoning blood.',questions:'Am I trusting Christ’s finished sacrifice, or my own works? What sin must I confess and forsake?',prayer:'Lamb of God, thank Thee for bearing sin once for all. Cleanse me and prepare me for Thy appearing.'},
'Passover':{theme:'Feasts',title:'Christ Our Passover',ref:'1 Corinthians 5:7–8',context:'Paul directly identifies Christ as our Passover.',exposition:'Deliverance is found under the blood of the Lamb. Christ’s sacrifice calls His redeemed people to put away the old leaven and walk in sincerity and truth.',application:'Put away one known form of spiritual leaven.',questions:'What old leaven contradicts my profession of faith?',prayer:'Lord Jesus, thank Thee for Thy saving blood; make my life sincere and true.'},
'Feast of Trumpets':{theme:'Feasts',title:'The Trumpet of God',ref:'1 Thessalonians 4:16–18',context:'The trumpet announces the Lord’s descent and the resurrection hope of believers.',exposition:'The feast awakens watchfulness. Our hope is not in earthly stability but in the return of Jesus Christ.',application:'Comfort another believer with the promise of Christ’s return.',questions:'Am I living ready for the Lord’s appearing?',prayer:'Lord Jesus, keep me watchful and faithful until Thou comest.'},
'Feast of Tabernacles':{theme:'Feasts',title:'The Word Dwelt Among Us',ref:'John 1:14',context:'God dwelling with His people finds its glorious centre in the Word made flesh.',exposition:'Jesus Christ revealed the Father’s glory, full of grace and truth. The feast directs our hope toward God dwelling eternally with His redeemed.',application:'Welcome Christ’s rule into an area you have kept for yourself.',questions:'Does my life reflect His grace and truth?',prayer:'Lord Jesus, dwell richly in me and reveal Thy glory through obedient faith.'},
'Pentecost':{theme:'Feasts',title:'Power to Be Witnesses',ref:'Acts 1:8',context:'The risen Christ promised power from the Holy Ghost for worldwide witness.',exposition:'The Spirit does not magnify human personalities; He empowers testimony concerning Jesus Christ.',application:'Speak faithfully of Christ to one person.',questions:'Am I seeking spiritual power to exalt Christ or myself?',prayer:'Lord, fill and guide me to be a faithful witness unto Jesus Christ.'},
'Seventh-Day Sabbath':{theme:'Sabbath',title:'The Lord of Holy Rest',ref:'Mark 2:27–28',context:'Jesus declared both the gift and the true Lordship of the Sabbath.',exposition:'The Sabbath was made for man, yet it belongs under Christ’s authority. Worship, mercy, rest and Scripture should direct the heart toward Him.',application:'Protect holy time for worship, mercy and fellowship with Christ.',questions:'What will help this Sabbath centre more fully upon Jesus?',prayer:'Lord of the Sabbath, rule my time and teach me to delight in Thee.'}};return map[e.name]||null}
function devotionalsFor(date){const base=DEVOTIONAL_WEEKS[date.getDay()].map(x=>({...x})),feast=feastDevotional(date);if(feast)base[2]={type:'Biblical Calendar',...feast};return base}
function scriptureButton(ref){return `<button class="scripture-link" type="button" data-scripture="${escapeHtml(ref)}">${escapeHtml(ref)} KJV</button>`}
function devotionalCard(d,index,date,compact=false){return `<article class="devotional-card ${compact?'compact':''}"><p class="eyebrow">${d.type} · ${d.theme}</p><h2>${d.title}</h2>${scriptureButton(d.ref)}${compact?`<p>${d.exposition}</p>`:`<h3>Context</h3><p>${d.context}</p><h3>Christ-centred meditation</h3><p>${d.exposition}</p><h3>Personal application</h3><p>${d.application}</p><h3>Reflection questions</h3><p>${d.questions}</p><div class="devotional-prayer"><h3>Prayer</h3><p>${d.prayer}</p></div><div class="devotional-actions"><button class="btn outline open-soap" type="button">Open SOAP Study</button><button class="btn navy email-devotional" type="button" data-devotional="${index}">Email This Devotional — Free</button></div><p class="status"></p>`}</article>`}
async function devotionalTranslationCard(d,lang){
  const name=LANG[lang]||lang;
  const fields=await Promise.all([d.type,d.theme,d.title,'Context',d.context,'Christ-centred meditation',d.exposition,'Personal application',d.application,'Reflection questions',d.questions,'Prayer',d.prayer].map(x=>translate(x,lang)));
  return `<article class="devotional-translation" lang="${escapeHtml(lang)}"><p class="eyebrow">${escapeHtml(fields[0])} · ${escapeHtml(fields[1])} · ${escapeHtml(name)}</p><h2>${escapeHtml(fields[2])}</h2><p class="translated-scripture-ref">${escapeHtml(d.ref)} KJV · English Scripture reference</p><h3>${escapeHtml(fields[3])}</h3><p>${escapeHtml(fields[4])}</p><h3>${escapeHtml(fields[5])}</h3><p>${escapeHtml(fields[6])}</p><h3>${escapeHtml(fields[7])}</h3><p>${escapeHtml(fields[8])}</p><h3>${escapeHtml(fields[9])}</h3><p>${escapeHtml(fields[10])}</p><div class="devotional-prayer"><h3>${escapeHtml(fields[11])}</h3><p>${escapeHtml(fields[12])}</p></div></article>`;
}
async function renderDevotionals(){
  const list=devotionalsFor(devotionalDate),event=eventFor(devotionalDate),lang=$('#site-language')?.value||'en';
  $('#devotional-date').textContent=dateLabel(devotionalDate);
  $('#devotional-calendar-note').textContent=event?`${event.name} · devotionals emphasize ${event.theme}`:'Morning, evening and discipleship readings';
  $('#daily-devotionals').innerHTML=list.map((d,i)=>`<div class="devotional-bilingual"><div class="devotional-english notranslate" translate="no">${devotionalCard(d,i,devotionalDate)}</div><div class="devotional-selected-language" data-devotional-translation="${i}">${lang==='en'?'':`<article class="devotional-translation loading"><p>Translating devotional…</p></article>`}</div></div>`).join('');
  bindDevotionalActions(list);
  $('#next-devotional-day').disabled=dateLabel(devotionalDate)===dateLabel(new Date());
  if(lang!=='en'){
    await Promise.all(list.map(async(d,i)=>{const box=document.querySelector(`[data-devotional-translation="${i}"]`);if(box)box.innerHTML=await devotionalTranslationCard(d,lang)}));
  }
}
function bindDevotionalActions(list){$$('.scripture-link').forEach(b=>b.onclick=()=>openDevotionalScripture(b.dataset.scripture));$$('.open-soap').forEach(b=>b.onclick=()=>{location.hash='home';setTimeout(()=>$('#day-section')?.scrollIntoView({behavior:'smooth'}),100)});$$('.email-devotional').forEach(b=>b.onclick=()=>{const d=list[Number(b.dataset.devotional)],card=b.closest('.devotional-card');emailPrivate('Devotional',`${d.type.toUpperCase()} DEVOTIONAL\n${d.title}\n${d.ref} KJV\n\nCONTEXT\n${d.context}\n\nMEDITATION\n${d.exposition}\n\nAPPLICATION\n${d.application}\n\nQUESTIONS\n${d.questions}\n\nPRAYER\n${d.prayer}`,card.querySelector('.status'))})}
async function openDevotionalScripture(ref){const m=ref.match(/^(.+?)\s(\d+):(\d+)(?:[–-](\d+))?$/);if(!m)return;book=m[1];chapter=Number(m[2]);verse=Number(m[3]);highlightEnd=Number(m[4]||m[3]);$('#book-select').value=book;populateChapters();$('#chapter-select').value=chapter;populateVerses();$('#verse-select').value=verse;location.hash='bible';await renderFullChapter();$$('#chapter-en p,#chapter-tr p').forEach(p=>{const v=Number(p.dataset.v||p.querySelector('sup')?.textContent);p.classList.toggle('selected',v>=verse&&v<=highlightEnd)});setTimeout(()=>$('#chapter-en .selected')?.scrollIntoView({block:'center'}),100)}
function devotionalArchive(){return DEVOTIONAL_WEEKS.flat()}
function searchDevotionals(){const q=$('#devotional-keyword').value.trim().toLowerCase(),theme=$('#devotional-theme').value,type=$('#devotional-type').value,scripture=$('#devotional-scripture').value.trim().toLowerCase();const results=devotionalArchive().filter(d=>{const text=Object.values(d).join(' ').toLowerCase();return(!q||text.includes(q))&&(theme==='all'||d.theme===theme)&&(type==='all'||d.type===type)&&(!scripture||d.ref.toLowerCase().includes(scripture))});$('#devotional-search-status').textContent=`${results.length} devotional${results.length===1?'':'s'} found.`;$('#devotional-archive').innerHTML=results.map(d=>devotionalCard(d,0,new Date(),true)).join('')||'<p>No devotionals match those search terms.</p>';$$('#devotional-archive .scripture-link').forEach(b=>b.onclick=()=>openDevotionalScripture(b.dataset.scripture))}
function initDevotionals(){devotionalDate=new Date();renderDevotionals();$('#previous-devotional-day').onclick=()=>{devotionalDate.setDate(devotionalDate.getDate()-1);renderDevotionals()};$('#next-devotional-day').onclick=()=>{const tomorrow=new Date(devotionalDate);tomorrow.setDate(tomorrow.getDate()+1);if(tomorrow<=new Date()){devotionalDate=tomorrow;renderDevotionals()}};$('#search-devotionals').onclick=searchDevotionals;['devotional-keyword','devotional-scripture'].forEach(id=>$(`#${id}`).onkeydown=e=>{if(e.key==='Enter')searchDevotionals()});$('#clear-devotionals').onclick=()=>{$('#devotional-keyword').value='';$('#devotional-scripture').value='';$('#devotional-theme').value=$('#devotional-type').value='all';searchDevotionals()};searchDevotionals()}
function initHymnSearch(){$('#hymn-search').onkeydown=e=>{if(e.key==='Enter')executeHymnSearch()};$('#hymn-scripture').onkeydown=e=>{if(e.key==='Enter')executeHymnSearch()};$('#search-hymns').onclick=executeHymnSearch;$('#search-hymns-web').onclick=searchHymnsOnWeb;$('#clear-hymn-search').onclick=clearHymnSearch}
function events(){window.addEventListener('hashchange',route);$('#site-language').onchange=e=>applyInterfaceLanguage(e.target.value);$('#book-select').onchange=e=>{book=e.target.value;chapter=verse=1;populateChapters();renderSingle()};$('#chapter-select').onchange=e=>{chapter=+e.target.value;verse=1;populateVerses();renderSingle()};$('#verse-select').onchange=e=>{verse=+e.target.value;renderSingle()};$('#prev-verse').onclick=()=>moveVerse(-1);$('#next-verse').onclick=()=>moveVerse(1);$('#full-chapter').onclick=()=>renderFullChapter();$('#close-chapter').onclick=renderSingle;$('#prev-chapter').onclick=()=>moveChapter(-1);$('#next-chapter').onclick=()=>moveChapter(1);$('#hymn-search').oninput=renderHymns;$('#hymn-filter').onchange=renderHymns;$('#donate').onclick=()=>$('#donate-status').textContent='The secure Flik payment gateway will become available after the ministry’s merchant account and checkout credentials are approved and connected. No payment information has been collected.'}

function initPrayerReader(){
  const text=$('#prayer-text'),name=$('#prayer-name'),voice=$('#prayer-voice'),rate=$('#prayer-rate'),pitch=$('#prayer-pitch'),status=$('#prayer-status'),list=$('#saved-prayer-list');
  if(!text)return;
  let utter=null,prayers=[];
  try{prayers=JSON.parse(localStorage.getItem('lots-prayers')||'[]')}catch{prayers=[]}
  const synth=('speechSynthesis' in window)?window.speechSynthesis:null;
  const save=()=>localStorage.setItem('lots-prayers',JSON.stringify(prayers));
  const voices=()=>{if(!synth)return;const all=synth.getVoices();voice.innerHTML='<option value="">Device default</option>'+all.map((v,i)=>`<option value="${i}">${v.name} · ${v.lang}</option>`).join('')};
  voices();if(synth)synth.onvoiceschanged=voices;
  const speak=()=>{
    const value=text.value.trim();
    if(!value){status.textContent='Paste or type a prayer first.';return}
    if(!synth||!('SpeechSynthesisUtterance' in window)){status.textContent='Read aloud is not supported by this browser.';return}
    synth.cancel();
    const all=synth.getVoices(),selected=voice.value===''?null:all[Number(voice.value)];
    // Mobile speech engines often reject or silently stop very long utterances.
    // Read the prayer in short sentence-sized chunks instead.
    const chunks=(value.match(/[^.!?\n]+[.!?]+|[^.!?\n]+$/g)||[value])
      .map(x=>x.trim()).filter(Boolean)
      .flatMap(x=>x.length<=220?[x]:(x.match(/.{1,220}(?:\s|$)/g)||[x]).map(y=>y.trim()).filter(Boolean));
    let part=0,stopped=false;
    const readNext=()=>{
      if(stopped||part>=chunks.length){if(!stopped)status.textContent='Prayer reading finished.';return}
      utter=new SpeechSynthesisUtterance(chunks[part]);
      utter.rate=Number(rate.value)||1;
      utter.pitch=Number(pitch?.value)||1;
      if(selected)utter.voice=selected;
      utter.onstart=()=>status.textContent='Reading prayer aloud… '+(part+1)+'/'+chunks.length;
      utter.onend=()=>{part++;setTimeout(readNext,80)};
      utter.onerror=e=>{
        const err=e?.error||'unknown';
        // Android may occasionally time out between long-prayer chunks. Retry the
        // current chunk once, then continue rather than abandoning the whole prayer.
        if((err==='interrupted'||err==='canceled'||err==='network')&&!stopped){
          setTimeout(readNext,180);return;
        }
        status.textContent='Prayer reader stopped ('+err+').';
      };
      synth.speak(utter);
    };
    window.__stopPrayerReader=()=>{stopped=true;synth.cancel()};
    readNext();
    setTimeout(()=>{if(synth.paused)synth.resume()},50);
  };
  const render=()=>{const q=($('#prayer-search').value||'').toLowerCase();const rows=prayers.map((p,i)=>({...p,i})).filter(p=>!q||p.name.toLowerCase().includes(q)||p.text.toLowerCase().includes(q));list.innerHTML=rows.length?rows.map(p=>`<article class="saved-prayer"><button class="saved-prayer-open" data-i="${p.i}" type="button"><strong>${escapeHtml(p.name)}</strong><span>${escapeHtml(p.text.slice(0,120))}${p.text.length>120?'…':''}</span></button><button class="saved-prayer-delete" data-i="${p.i}" type="button" aria-label="Delete ${escapeHtml(p.name)}">Delete</button></article>`).join(''):'<p>No saved prayers yet.</p>';document.querySelectorAll('.saved-prayer-open').forEach(b=>b.onclick=()=>{const p=prayers[+b.dataset.i];name.value=p.name;text.value=p.text;text.focus()});document.querySelectorAll('.saved-prayer-delete').forEach(b=>b.onclick=()=>{prayers.splice(+b.dataset.i,1);save();render()})};
  $('#prayer-play').onclick=speak;
  $('#prayer-pause').onclick=()=>{if(synth){synth.pause();status.textContent='Prayer paused.'}};
  $('#prayer-resume').onclick=()=>{if(synth){synth.resume();status.textContent='Prayer resumed.'}};
  $('#prayer-stop').onclick=()=>{if(synth){if(window.__stopPrayerReader)window.__stopPrayerReader();else synth.cancel();status.textContent='Prayer stopped.'}};
  $('#prayer-restart').onclick=()=>{if(synth){if(window.__stopPrayerReader)window.__stopPrayerReader();else synth.cancel()}speak()};
  rate.oninput=()=>$('#prayer-rate-value').textContent=rate.value+'×';
  if(pitch)pitch.oninput=()=>$('#prayer-pitch-value').textContent=Number(pitch.value).toFixed(1)+'×';
  const preview=$('#preview-prayer-voice');
  if(preview)preview.onclick=()=>{
    if(!synth||!('SpeechSynthesisUtterance' in window)){status.textContent='Voice preview is not supported by this browser.';return}
    synth.cancel();
    const sample=new SpeechSynthesisUtterance('The Lord bless thee, and keep thee.');
    sample.rate=Number(rate.value)||1;sample.pitch=Number(pitch?.value)||1;
    const all=synth.getVoices(),selected=voice.value===''?null:all[Number(voice.value)];
    if(selected)sample.voice=selected;
    sample.onstart=()=>status.textContent='Previewing '+(selected?selected.name:'device default')+'…';
    sample.onend=()=>status.textContent='Voice preview finished.';
    sample.onerror=e=>status.textContent='Voice preview stopped'+(e?.error?' ('+e.error+').':'.');
    synth.speak(sample);
  };
  $('#save-prayer').onclick=()=>{const value=text.value.trim();if(!value){status.textContent='Enter a prayer before saving.';return}const title=name.value.trim()||'Saved Prayer '+new Date().toLocaleDateString();prayers.unshift({name:title,text:value,updated:new Date().toISOString()});save();name.value=title;status.textContent='Prayer saved on this device.';render()};
  $('#prayer-search').oninput=render;
  render();
}
function scrollToDailyVerse(target){
  const go=()=>{
    const el=document.getElementById(target);
    if(!el)return;
    // Use an absolute document position instead of scrollIntoView; this is more reliable
    // in Android browsers and after browser scroll-position restoration.
    const y=el.getBoundingClientRect().top+window.scrollY-8;
    window.scrollTo({top:Math.max(0,y),left:0,behavior:'instant'});
  };
  go();
  requestAnimationFrame(()=>requestAnimationFrame(go));
  setTimeout(go,250);
  setTimeout(go,1000);
  setTimeout(go,2000);
}
function autoScrollDailyVerse(){
  const hash=location.hash.slice(1);
  const requestedPage=hash&&document.getElementById(hash);
  if(hash&&hash!=='home'&&requestedPage?.classList.contains('page'))return;
  if('scrollRestoration' in history)history.scrollRestoration='manual';
  const now=new Date();
  const fallback=()=>{const h=now.getHours();return h>=6&&h<18?'day-section':'night-section'};
  const land=target=>{
    history.replaceState(null,'','#'+target);
    const go=()=>document.getElementById(target)?.scrollIntoView({block:'start',behavior:'auto'});
    go();requestAnimationFrame(()=>requestAnimationFrame(go));setTimeout(go,250);
  };
  // Land immediately; refine to the user's actual local sunrise/sunset if location is permitted.
  land(fallback());
  if(!navigator.geolocation)return;
  navigator.geolocation.getCurrentPosition(async pos=>{
    try{
      const {latitude,longitude}=pos.coords;
      const date=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
      const r=await fetch(`https://api.sunrise-sunset.org/json?lat=${latitude}&lng=${longitude}&date=${date}&formatted=0`,{cache:'no-store'});
      const d=await r.json(),sunrise=Date.parse(d?.results?.sunrise),sunset=Date.parse(d?.results?.sunset);
      if(d?.status==='OK'&&!Number.isNaN(sunrise)&&!Number.isNaN(sunset))land(now.getTime()>=sunrise&&now.getTime()<sunset?'day-section':'night-section');
    }catch{}
  },()=>{}, {timeout:3500,maximumAge:21600000});
}
async function init(){
  // Build each feature independently so one broken optional module cannot disable the rest.
  try{buildStatic()}catch(e){console.error('buildStatic',e)}
  try{if(today.event===EVENTS.atonement)$('#daily-mount')?.insertAdjacentHTML('afterbegin',feastFeature())}catch(e){console.error('feast',e)}
  try{initPrayerReader()}catch(e){console.error('prayer reader',e)}
  try{route()}catch(e){console.error('route',e)}
  try{autoScrollDailyVerse()}catch(e){console.error('daily landing',e)}
  try{const y=$('#year');if(y)y.textContent=new Date().getFullYear()}catch(e){}

  // Load KJV before initializing features that depend on Scripture.
  try{
    const r=await fetch('assets/kjv-1769.json?v=20260922-2',{cache:'no-store'});
    if(!r.ok)throw Error('KJV data unavailable');
    bible=await r.json();
    populateBooks();
    renderSingle();
    ['day','night'].forEach(k=>{
      const ref=today[k],v=getVerse(...Object.values(parseRef(ref))),el=$(`#${k}-en`);
      if(el)el.textContent=v?`“${v}”`:'Scripture unavailable.';
    });
    renderHymns();
  }catch(e){
    console.error('Bible data',e);
    ['day','night'].forEach(k=>{const el=$(`#${k}-en`);if(el)el.textContent='KJV Scripture could not be loaded.'});
  }

  try{events()}catch(e){console.error('events',e)}
  try{initHymnSearch();loadPublicDomainHymnCatalog()}catch(e){console.error('hymns',e)}
  try{const savedLang=localStorage.getItem('lots-language')||'en',sel=$('#site-language');if(sel&&[...sel.options].some(o=>o.value===savedLang)){sel.value=savedLang;refreshTranslations(savedLang)}}catch(e){console.error('language restore',e)}
  try{initDevotionals()}catch(e){console.error('devotionals',e)}
  try{initFinance()}catch(e){console.error('finance',e)}
  try{initTodos()}catch(e){console.error('todos',e)}
  try{loadPrivateData()}catch(e){console.error('private data',e)}
  window.addEventListener('keydown',e=>{if(e.key==='Escape')try{closeHymn()}catch{}});
  setTimeout(()=>{const combo=$('.goog-te-combo');if(combo)combo.setAttribute('aria-label','Google website translation')},2500);
}
init();
